<!doctype html>
<html>

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <title>mini</title>
  {qcms_style id="210536917" name="reset"} {qcms_style id="490964737" name="rediantoutiao"} {qcms_style id="490964744" name="mini_nav"} {qcms_style id="210536931" name="video_live"} {qcms_style id="210536933" name="video_flow"} {qcms_style id="490964750" name="showcase"}
  <style type="text/css">
  #tab_shop iframe {
    position: relative;
    top: -9px;
    left:-20px;
  }

  .spages .spage-2 {
    position: relative;
    _position: static;
    z-index: 101;
    background-color: #fff;
  }

  .doc-bd {
    _width: 750px;
    _height: 502px;
    _overflow: hidden;
    height: 502px
  }

  .page {
    *z-index: 111;
  }

  .page-scrollbar .scrollbar,
  .page_home {
    z-index: 111;
  }

  .technical {
    _bottom: 4px;
  }
  /* 小图推荐广告的重播按钮 liuguanyu 2017-09-12*/

  .btn-replay-small {
    top: 110px;
  }

  /* 鲁大师 */
  .wrapper {
    height: 552px;
  }
  #doc-bd .content {
    padding-top: 10px;
    height: 486px;
  }
  .page {
    height: 496px;
  }
  .page-scrollbar .scrollbar {
    background-size: 100% 100%;
  }
  .page-scrollbar .viewport {
    height: 486px;
  }
  .spages .spage-1 {
    height: 486px;
  }
  .technical {
    bottom: -9px;
    right: 21px;
  }
  .technical:hover {
    color: #049;
  }
  .newsflow-tips {
    bottom: 10px;
  }
  </style>
  <base target="_blank">
  <script>
  var startTime = new Date().getTime();
  try {
    external.Show(750, 552);
  } catch (err) {}
  </script>
</head>

<body>
  <div class="wrapper">
    <div class="doc-hd" id="doc-hd">
      <p class="logo f-l">
        <img src="http://p2.qhimg.com/t0196d3d0b214e8c6eb.png" alt="logo">
      </p>
      <p class="opteration f-r">
        <a href="#" class="setting"></a>
        <a href="#" class="min"></a>
        <a href="#" class="close"></a>
      </p>
    </div>
    <div class="mini_header">
      <p class="handover"><span><a href="javascript:void(0);">更多</a></span><i></i></p>
      <ul class="nav" id="nav">
        <li><a href="http://sh.qihoo.com/pc/home?ch=youlike&sign=ex_40895b4c" name="推荐" id="nav_rec" class="cur" bk="nav_rec" bk_baodian="nav_youlike">推荐</a></li>
        <!-- <li class="nav-li-video"><a href="http://k.360kan.com/pc/list?dl=llq_tc_sp&from=mini" name="视频" id="nav_video" bk="nav_video">视频</a></li> -->
        <li><a href="http://sh.qihoo.com/pc/home?ch=domestic&sign=ex_40895b4c" name="新闻" id="nav_news" bk="nav_news" bk_baodian="nav_youlike">新闻</a></li>
        <li><a href="http://sh.qihoo.com/pc/home?ch=fun&sign=ex_40895b4c" name="娱乐" id="nav_ent" bk="nav_ent" bk_baodian="nav_fun">娱乐</a></li>
        <li><a href="http://sh.qihoo.com/pc/home?ch=militery&sign=ex_40895b4c" name="军事" id="nav_military" bk="nav_military" bk_baodian="nav_militery">军事</a></li>
        <!-- <li><a href="http://hao.360.cn/sub/resou.html" name="精选" id="nav_lianmeng" bk="nav_lianmeng">精选</a></li> -->
        <li><a href="http://sh.qihoo.com/pc/home?ch=car&sign=ex_40895b4c" name="汽车" id="nav_car" bk="nav_car" bk_baodian="nav_car">汽车</a></li>
        <li><a href="http://sh.qihoo.com/pc/home?ch=economy&sign=ex_40895b4c" name="财经" id="nav_finance" bk="nav_finance" bk_baodian="nav_economy">财经</a></li>
        <li><a href="http://sh.qihoo.com/pc/home?ch=sport&sign=ex_40895b4c" name="体育" id="nav_sports" bk="nav_sports" bk_baodian="nav_sport">体育</a></li>
        <li><a href="http://sh.qihoo.com/pc/home?ch=social&sign=ex_40895b4c" name="社会" id="nav_society" bk="nav_society" bk_baodian="nav_social">社会</a></li>
        <li><a href="https://s.click.taobao.com/t?e=m%3D2%26s%3Dx3kIKqqZx5McQipKwQzePCperVdZeJvi7UTzUAW%2BpR4YX8TY%2BNEwd%2Bn3FA4bNS08Nq%2BDna%2F8eQejQ9birlUo6LkKf0S1XgMDhp0WNL7aIKbVqmasEvMO2KeCIdaTy7El52aaZdY%2B947kxFiXT%2FI5kUH3IB4mwY%2B0s3jKxCkW%2BjFyeNAoQluSal53NB9MJeYJKVz9LNlhQoGA%2BtmZUvkmY2yVYWzUSWUJ6yiYwQfONoA%3D" name="购物" id="nav_shop" bk="nav_shop">购物</a></li>
        <!-- <li><a href="http://xiaohua.360.cn/?from=mini" name="笑话" id="nav_joke" bk="nav_joke">笑话</a></li> -->
        <li><a href="http://sh.qihoo.com/pc/home?ch=probe&sign=ex_40895b4c" name="科技" id="nav_tec" bk="nav_tec" bk_baodian="nav_science">科技</a></li>
        <li><a href="http://sh.qihoo.com/pc/home?ch=zodiac&sign=ex_40895b4c" name="星座" id="nav_constellation" bk="nav_constellation" bk_baodian="nav_zodiac">星座</a></li>
        <!-- <li><a href="http://www.360kan.com?from=mini" name="影视" id="nav_movie" bk="nav_movie">影视</a></li> -->
        <li><a href="http://sh.qihoo.com/pc/home?ch=science&sign=ex_40895b4c" name="数码" id="nav_digital" bk="nav_digital" bk_baodian="nav_youlike">数码</a></li>
        <li><a href="http://sh.qihoo.com/pc/home?ch=food&sign=ex_40895b4c" name="生活" id="nav_life" bk="nav_life" bk_baodian="nav_youlike">生活</a></li>
        <li><a href="http://sh.qihoo.com/pc/home?ch=fashion&sign=ex_40895b4c" name="时尚" id="nav_fashion" bk="nav_fashion" bk_baodian="nav_fashion">时尚</a></li>
        <!-- <li><a href="http://www.huajiao.com?from=mini&qd=mini" name="直播" id="nav_live" bk="nav_live">直播</a></li> -->
        <li><a href="http://sh.qihoo.com/pc/home?ch=history&sign=ex_40895b4c" name="文化" id="nav_culture" bk="nav_culture" bk_baodian="nav_history">文化</a></li>
        <!-- <li><a href="http://u.360.cn/?from=mini" name="游戏" id="nav_game" bk="nav_game">游戏</a></li> -->
        <!-- <li><a href="http://u.360.cn/?from=mini" name="手游" id="nav_mobilegames" bk="nav_mobilegames">手游</a></li> -->
        <!-- <li><a href="http://mini.eastday.com/?qid=360mini" name="奇闻" id="nav_anecdote" bk="nav_anecdote">奇闻</a></li> -->
      </ul>
    </div>
    <div class="doc-bd" id="doc-bd">
      <div class="content">
        <div class="page" id="tab_rec" bk="mini_rec">
          <div class="page-scrollbar">
            <div class="page_home"></div>
            <div class="scrollbar">
              <div class="track">
                <div class="thumb">
                  <div class="end"></div>
                </div>
              </div>
            </div>
            <div class="viewport">
              <div class="overview">
                <div class="spages">
                  <div class="spage-1" bk="mini_rec_page1">
                    <div class="l f-l">
                      <div bk="news_pic_left">
                        {qcms_block id="210512439" dtid="210386472" count="1" width="180" height="194" qcms-custom-preview="1"}
                      </div>
                      <div bk="ent_pic">
                        {qcms_block id="210512439" dtid="490680315" count="2" width="180" height="100" qcms-custom-preview="1"}
                      </div>
                      {qcms_block id="210512439" dtid="490919689" count="1" width="180" height="68" qcms-custom-preview="1"}
                    </div>
                    <div class="m f-l">
                      <div class="news">
                        <div bk="news_text_top" class="news-top">
                          {qcms_block id="210512626" dtid="210386496" count="1" qcms-custom-preview="1"} {qcms_block id="490919637" dtid="490680507" count="5" qcms-custom-preview="1"}
                        </div>
                        <div bk="news_text_center">
                          {qcms_block id="210512626" dtid="490680325" count="1" qcms-custom-preview="1"} {qcms_block id="490919637" dtid="490680479" count="5" qcms-custom-preview="1"}
                        </div>
                        <div bk="ent_text">
                          {qcms_block id="210512626" dtid="210386498" count="1" qcms-custom-preview="1"} {qcms_block id="490919637" dtid="490680512" count="4" qcms-custom-preview="1"}
                        </div>
                      </div>
                    </div>
                    <div class="r f-l/* r-fix*/">
                      <div class="relative" bk="recommend_right_ads_big">
                        {qcms_block id="490964780" dtid="210386508" count="1" width="180" height="274" qcms-custom-preview="1"}
                        <div class="btn-replay">重播</div>
                      </div>
                      <div class="relative" bk="recommend_right_ads_small">
                        {qcms_block id="490964780" dtid="210386518" count="1" width="180" height="128" qcms-custom-preview="1"}
                        <div class="btn-replay btn-replay-small">重播</div>
                      </div>
                      <div class="relative" bk="recommend_right_ads_bottom">
                        {qcms_block id="210512439" dtid="490920333" count="1" width="180" height="68" qcms-custom-preview="1"}
                      </div>
                    </div>
                  </div>
                  <div class="spage-2" bk="mini_rec_page2" data-target="rec_page2">
                    <div class="news-container">
                      <ul class="news-content-wrapper">
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="newsflow-tips">
              <img src="http://p7.qhimg.com/d/inn/9f3465b4/odot.png" class="odot"> 更多未读资讯
              <img src="http://p6.qhimg.com/d/inn/9ca1c978/arrow.gif" width="12" height="19">
              <i></i>
            </div>
          </div>
        </div>
        <!-- <div class="page" id="tab_video" bk="mini_video">
          <div class="page-scrollbar">
            <div class="page_home"></div>
            <div class="scrollbar">
              <div class="track">
                <div class="thumb">
                  <div class="end"></div>
                </div>
              </div>
            </div>
            <div class="viewport">
              <div class="overview">
                <div class="spages">
                  <div class="spage-1" bk="mini_video_page1">
                    <div class="l f-l">
                      <div bk="video_left_ads_big">
                        {qcms_block id="490964780" dtid="210240491" count="1" width="180" height="194" qcms-custom-preview="1"}
                      </div>
                      <div bk="video_left_ads_small_1">
                        {qcms_block id="490964780" dtid="210240489" count="1" width="180" height="100" qcms-custom-preview="1"}
                      </div>
                      <div bk="video_left_ads_small_2">
                        {qcms_block id="490964780" dtid="210240487" count="1" width="180" height="100" qcms-custom-preview="1"}
                      </div>
                    </div>
                    <div class="m f-l">
                      <div class="news">
                        <div bk="video_text_top" class="news-top">
                        {qcms_block id="210512626" dtid="490835413" count="5" qcms-custom-preview="1"}
                        </div>
                        <div bk="video_text_center">
                        {qcms_block id="210512626" dtid="210467969" count="5" qcms-custom-preview="1"}
                        </div>
                        <div bk="video_text_bottom">
                        {qcms_block id="210512626" dtid="210467973" count="5" qcms-custom-preview="1"}
                        </div>
                      </div>
                    </div>
                    <div class="r f-l" bk="video_right">
                      {qcms_block id="210512439" dtid="210240485" count="1" width="180" height="194" qcms-custom-preview="1"} {qcms_block id="210512439" dtid="210240483" count="2" width="180" height="100" qcms-custom-preview="1"}
                    </div>
                  </div>
                  <div class="spage-2" bk="mini_video_page2" data-target="video_page2">
                    <div class="news-container">
                      <ul class="news-content-wrapper">
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="newsflow-tips">
              <img src="http://p7.qhimg.com/d/inn/9f3465b4/odot.png" class="odot"> 更多未读资讯
              <img src="http://p6.qhimg.com/d/inn/9ca1c978/arrow.gif" width="12" height="19">
              <i></i>
            </div>
          </div>
        </div> -->
        <div class="page" id="tab_news" bk="mini_news">
          <div class="page-scrollbar">
            <div class="page_home"></div>
            <div class="scrollbar">
              <div class="track">
                <div class="thumb">
                  <div class="end"></div>
                </div>
              </div>
            </div>
            <div class="viewport">
              <div class="overview">
                <div class="spages">
                  <div class="spage-1" bk="mini_news_page1">
                    <div class="l f-l">
                      {qcms_block id="210512439" dtid="490680392" count="1" width="180" height="194" qcms-custom-preview="1"} {qcms_block id="210512439" dtid="490680408" count="2" width="180" height="100" qcms-custom-preview="1"}
                      {qcms_block id="210512439" dtid="490919741" count="1" width="180" height="68" qcms-custom-preview="1"}
                      <!-- 15:52 -->
                    </div>
                    <div class="m f-l">
                      <div class="news">
                        <div class="news-top">
                          {qcms_block id="210512626" dtid="490680430" count="1" qcms-custom-preview="1"} {qcms_block id="490919637" dtid="210386612" count="6" qcms-custom-preview="1"}
                          <!-- 16:00 -->
                        </div>
                        <div>
                          {qcms_block id="210512626" dtid="210392378" count="1" qcms-custom-preview="1"} {qcms_block id="490919637" dtid="210386606" count="3" qcms-custom-preview="1"}
                        </div>
                        <div>
                          {qcms_block id="210512626" dtid="210386593" count="1" qcms-custom-preview="1"} {qcms_block id="490919637" dtid="490680450" count="5" qcms-custom-preview="1"}
                        </div>
                      </div>
                    </div>
                    <div class="r f-l" bk="news_right">
                      {qcms_block id="210512439" dtid="210386601" count="1" width="180" height="194" qcms-custom-preview="1"} {qcms_block id="210512439" dtid="490680446" count="2" width="180" height="100" qcms-custom-preview="1"}
                      {qcms_block id="210512439" dtid="490919899" count="1" width="180" height="68" qcms-custom-preview="1"}
                    </div>
                  </div>
                  <div class="spage-2" bk="mini_news_page2" data-target="news_page2">
                    <div class="news-container">
                      <ul class="news-content-wrapper">
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="newsflow-tips">
              <img src="http://p7.qhimg.com/d/inn/9f3465b4/odot.png" class="odot"> 更多未读资讯
              <img src="http://p6.qhimg.com/d/inn/9ca1c978/arrow.gif" width="12" height="19">
              <i></i>
            </div>
          </div>
        </div>
        <!-- <div class="page" id="tab_game" bk="mini_game">
          <div class="page-scrollbar">
            <div class="page_home"></div>
            <div class="scrollbar">
              <div class="track">
                <div class="thumb">
                  <div class="end"></div>
                </div>
              </div>
            </div>
            <div class="viewport">
              <div class="overview">
                <div class="spages">
                  <div class="spage-1" bk="mini_game_page1">
                    <div class="l f-l">
                      <div bk="game_left_ads_big">
                        {qcms_block id="490964780" dtid="490293438" count="1" width="180" height="194" qcms-custom-preview="1"}
                      </div>
                      <div bk="game_left_ads_small_1">
                        {qcms_block id="490964780" dtid="490293442" count="1" width="180" height="100" qcms-custom-preview="1"}
                      </div>
                      <div bk="game_left_ads_small_2">
                        {qcms_block id="490964780" dtid="490296925" count="1" width="180" height="100" qcms-custom-preview="1"}
                      </div>
                    </div>
                    <div class="m f-l">
                      <div class="news">
                        <div bk="game_text_top" class="news-top">
                          {qcms_block id="210512626" dtid="490293450" count="1" qcms-custom-preview="1"} {qcms_block id="490919637" dtid="490293453" count="4" qcms-custom-preview="1"}
                        </div>
                        <div bk="game_text_center">
                          {qcms_block id="210512626" dtid="490293455" count="1" qcms-custom-preview="1"} {qcms_block id="490919637" dtid="490293457" count="4" qcms-custom-preview="1"}
                        </div>
                        <div bk="game_text_bottom">
                          {qcms_block id="210512626" dtid="490293459" count="1" qcms-custom-preview="1"} {qcms_block id="490919637" dtid="490293463" count="4" qcms-custom-preview="1"}
                        </div>
                      </div>
                    </div>
                    <div class="r f-l" data-showcase=".showcase-2">
                      <div bk="game_right_ads_big">
                        {qcms_block id="490964780" dtid="490293466" count="1" width="180" height="274" qcms-custom-preview="1"}
                      </div>
                      <div bk="game_right_ads_small">
                        {qcms_block id="490964780" dtid="490293469" count="1" width="180" height="128" qcms-custom-preview="1"}
                      </div>
                    </div>
                  </div>
                  <div class="spage-2" bk="mini_game_page2" data-target="game_page2">
                    <div class="news-container">
                      <ul class="news-content-wrapper">
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="newsflow-tips">
              <img src="http://p7.qhimg.com/d/inn/9f3465b4/odot.png" class="odot"> 更多未读资讯
              <img src="http://p6.qhimg.com/d/inn/9ca1c978/arrow.gif" width="12" height="19">
              <i></i>
            </div>
          </div>
        </div> -->
        <div class="page" id="tab_ent" bk="mini_ent">
          <div class="page-scrollbar">
            <div class="page_home"></div>
            <div class="scrollbar">
              <div class="track">
                <div class="thumb">
                  <div class="end"></div>
                </div>
              </div>
            </div>
            <div class="viewport">
              <div class="overview">
                <div class="spages">
                  <div class="spage-1" bk="mini_ent_page1">
                    <div class="l f-l" bk="ent_left">
                      <!-- 18:08 -->
                      {qcms_block id="210512439" dtid="490680909" count="1" width="180" height="194" qcms-custom-preview="1"} {qcms_block id="210512439" dtid="210386872" count="2" width="180" height="100" qcms-custom-preview="1"}
                      {qcms_block id="210512439" dtid="490919743" count="1" width="180" height="68" qcms-custom-preview="1"}
                    </div>
                    <div class="m f-l">
                      <div class="news">
                        <div class="news-top" bk="ent_text_top">
                          <!-- 18:12 -->
                          {qcms_block id="210512626" dtid="490680947" count="1" qcms-custom-preview="1"} {qcms_block id="490919637" dtid="490680955" count="6" qcms-custom-preview="1"}
                        </div>
                        <!-- 18:15 -->
                        <div bk="ent_text_center">
                          {qcms_block id="210512626" dtid="490685151" count="1" qcms-custom-preview="1"} {qcms_block id="490919637" dtid="490685161" count="3" qcms-custom-preview="1"}
                        </div>
                        <!-- 14:11 -->
                        <div bk="ent_text_bottom">
                          {qcms_block id="210512626" dtid="490685174" count="1" qcms-custom-preview="1"} {qcms_block id="490919637" dtid="490685190" count="5" qcms-custom-preview="1"}
                        </div>
                      </div>
                    </div>
                    <div class="r f-l">
                      <div bk="ent_right">
                        {qcms_block id="210512439" dtid="210389258" count="1" width="180" height="194" qcms-custom-preview="1"} {qcms_block id="210512439" dtid="490685202" count="2" width="180" height="100" qcms-custom-preview="1"}
                        {qcms_block id="210512439" dtid="210512874" count="1" width="180" height="68" qcms-custom-preview="1"}
                      </div>
                    </div>
                  </div>
                  <div class="spage-2" bk="mini_ent_page2" data-target="ent_page2">
                    <div class="news-container">
                      <ul class="news-content-wrapper">
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="newsflow-tips">
              <img src="http://p7.qhimg.com/d/inn/9f3465b4/odot.png" class="odot"> 更多未读资讯
              <img src="http://p6.qhimg.com/d/inn/9ca1c978/arrow.gif" width="12" height="19">
              <i></i>
            </div>
          </div>
        </div>
        <div class="page" id="tab_society" bk="mini_society">
          <div class="page-scrollbar">
            <div class="page_home"></div>
            <div class="scrollbar">
              <div class="track">
                <div class="thumb">
                  <div class="end"></div>
                </div>
              </div>
            </div>
            <div class="viewport">
              <div class="overview">
                <div class="spages">
                  <div class="spage-1" bk="mini_society_page1">
                    <div class="l f-l" bk="society_left">
                      <!-- 14:17 -->
                      {qcms_block id="210512439" dtid="490685206" count="1" width="180" height="194" qcms-custom-preview="1"} {qcms_block id="210512439" dtid="490685214" count="2" width="180" height="100" qcms-custom-preview="1"}
                      {qcms_block id="210512439" dtid="490919753" count="1" width="180" height="68" qcms-custom-preview="1"}
                    </div>
                    <div class="m f-l">
                      <div class="news">
                        <!-- 14:22 -->
                        <div bk="society_text_top" class="news-top">
                          {qcms_block id="210512626" dtid="490685227" count="1" qcms-custom-preview="1"} {qcms_block id="490919637" dtid="490685239" count="6" qcms-custom-preview="1"}
                        </div>
                        <!-- 14:28 -->
                        <div bk="society_text_center">
                          {qcms_block id="210512626" dtid="210389279" count="1" qcms-custom-preview="1"} {qcms_block id="490919637" dtid="490685253" count="3" qcms-custom-preview="1"}
                        </div>
                        <!-- 14:33 -->
                        <div bk="society_text_bottom">
                          {qcms_block id="210512626" dtid="490685392" count="1" qcms-custom-preview="1"} {qcms_block id="490919637" dtid="490686044" count="5" qcms-custom-preview="1"}
                        </div>
                        <!-- 18:31 -->
                      </div>
                    </div>
                    <div class="r f-l">
                      <div bk="society_right">
                        {qcms_block id="210512439" dtid="490686932" count="1" width="180" height="194" qcms-custom-preview="1"} {qcms_block id="210512439" dtid="490686982" count="2" width="180" height="100" qcms-custom-preview="1"}
                        {qcms_block id="210512439" dtid="210512884" count="1" width="180" height="68" qcms-custom-preview="1"}
                      </div>
                      <!-- 09:49 -->
                    </div>
                  </div>
                  <div class="spage-2" bk="mini_society_page2" data-target="society_page2">
                    <div class="news-container">
                      <ul class="news-content-wrapper">
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="newsflow-tips">
              <img src="http://p7.qhimg.com/d/inn/9f3465b4/odot.png" class="odot"> 更多未读资讯
              <img src="http://p6.qhimg.com/d/inn/9ca1c978/arrow.gif" width="12" height="19">
              <i></i>
            </div>
          </div>
        </div>
        <!-- <div class="page" id="tab_movie" bk="mini_movie">
          <div class="page-scrollbar">
            <div class="page_home"></div>
            <div class="scrollbar">
              <div class="track">
                <div class="thumb">
                  <div class="end"></div>
                </div>
              </div>
            </div>
            <div class="viewport">
              <div class="overview">
                <div class="spages">
                  <div class="spage-1" bk="mini_movie_page1">
                    <div class="l f-l" bk="movie_left">
                      {qcms_block id="210512439" dtid="490421962" count="1" width="180" height="194" qcms-custom-preview="1"} {qcms_block id="210512439" dtid="490421960" count="2" width="180" height="100" qcms-custom-preview="1"}
                    </div>
                    <div class="m f-l">
                      <div class="news">
                        <div bk="movie_text_top" class="news-top">
                          {qcms_block id="210512626" dtid="210249248" count="1" qcms-custom-preview="1"} {qcms_block id="490919637" dtid="210249246" count="6" qcms-custom-preview="1"}
                        </div>
                        <div bk="movie_text_center">
                          {qcms_block id="210512626" dtid="210249244" count="1" qcms-custom-preview="1"} {qcms_block id="490919637" dtid="210249242" count="3" qcms-custom-preview="1"}
                        </div>
                        <div bk="movie_text_bottom">
                          {qcms_block id="210512626" dtid="210249240" count="1" qcms-custom-preview="1"} {qcms_block id="490919637" dtid="210249237" count="3" qcms-custom-preview="1"}
                        </div>
                      </div>
                    </div>
                    <div class="r f-l">
                      <div bk="movie_right">
                        {qcms_block id="210512439" dtid="490421958" count="1" width="180" height="194" qcms-custom-preview="1"} {qcms_block id="210512439" dtid="210249250" count="2" width="180" height="100" qcms-custom-preview="1"}
                      </div>
                    </div>
                  </div>
                  <div class="spage-2" bk="mini_movie_page2" data-target="movie_page2">
                    <div class="news-container">
                      <ul class="news-content-wrapper">
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="newsflow-tips">
              <img src="http://p7.qhimg.com/d/inn/9f3465b4/odot.png" class="odot"> 更多未读资讯
              <img src="http://p6.qhimg.com/d/inn/9ca1c978/arrow.gif" width="12" height="19">
              <i></i>
            </div>
          </div>
        </div> -->
        <div class="page" id="tab_military" bk="mini_military">
          <div class="page-scrollbar">
            <div class="page_home"></div>
            <div class="scrollbar">
              <div class="track">
                <div class="thumb">
                  <div class="end"></div>
                </div>
              </div>
            </div>
            <div class="viewport">
              <div class="overview">
                <div class="spages">
                  <div class="spage-1" bk="mini_military_page1">
                    <div class="l f-l">
                      {qcms_block id="210512439" dtid="490687793" count="1" width="180" height="194" qcms-custom-preview="1"} {qcms_block id="210512439" dtid="490687797" count="2" width="180" height="100" qcms-custom-preview="1"}
                      {qcms_block id="210512439" dtid="490919745" count="1" width="180" height="68" qcms-custom-preview="1"}
                    </div>
                    <div class="m f-l">
                      <div class="news">
                        <div class="news-top">
                          {qcms_block id="210512626" dtid="490687802" count="1" qcms-custom-preview="1"} {qcms_block id="490919637" dtid="490687806" count="6" qcms-custom-preview="1"}
                        </div>
                        <div>
                          {qcms_block id="210512626" dtid="490687810" count="1" qcms-custom-preview="1"} {qcms_block id="490919637" dtid="490687825" count="3" qcms-custom-preview="1"}
                        </div>
                        <div>
                          {qcms_block id="210512626" dtid="490687836" count="1" qcms-custom-preview="1"} {qcms_block id="490919637" dtid="490687844" count="5" qcms-custom-preview="1"}
                        </div>
                      </div>
                    </div>
                    <div class="r f-l" bk="military_right">
                      {qcms_block id="210512439" dtid="490687868" count="1" width="180" height="194" qcms-custom-preview="1"} {qcms_block id="210512439" dtid="490687895" count="2" width="180" height="100" qcms-custom-preview="1"}
                      {qcms_block id="210512439" dtid="210512876" count="1" width="180" height="68" qcms-custom-preview="1"}
                    </div>
                  </div>
                  <div class="spage-2" bk="mini_military_page2" data-target="military_page2">
                    <div class="news-container">
                      <ul class="news-content-wrapper">
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="newsflow-tips">
              <img src="http://p7.qhimg.com/d/inn/9f3465b4/odot.png" class="odot"> 更多未读资讯
              <img src="http://p6.qhimg.com/d/inn/9ca1c978/arrow.gif" width="12" height="19">
              <i></i>
            </div>
          </div>
        </div>
        <div class="page" id="tab_life" bk="mini_life">
          <div class="page-scrollbar">
            <div class="page_home"></div>
            <div class="scrollbar">
              <div class="track">
                <div class="thumb">
                  <div class="end"></div>
                </div>
              </div>
            </div>
            <div class="viewport">
              <div class="overview">
                <div class="spages">
                  <div class="spage-1" bk="mini_life_page1">
                    <div class="l f-l">
                      {qcms_block id="210512439" dtid="490687905" count="1" width="180" height="194" qcms-custom-preview="1"} {qcms_block id="210512439" dtid="490687911" count="2" width="180" height="100" qcms-custom-preview="1"}
                      {qcms_block id="210512439" dtid="490919761" count="1" width="180" height="68" qcms-custom-preview="1"}
                    </div>
                    <div class="m f-l">
                      <div class="news">
                        <div class="news-top">
                          {qcms_block id="210512626" dtid="490687915" count="1" qcms-custom-preview="1"} {qcms_block id="490919637" dtid="490687919" count="6" qcms-custom-preview="1"}
                        </div>
                        <div>
                          {qcms_block id="210512626" dtid="490687923" count="1" qcms-custom-preview="1"} {qcms_block id="490919637" dtid="490687929" count="3" qcms-custom-preview="1"}
                        </div>
                        <div>
                          {qcms_block id="210512626" dtid="490687933" count="1" qcms-custom-preview="1"} {qcms_block id="490919637" dtid="490687940" count="5" qcms-custom-preview="1"}
                        </div>
                      </div>
                    </div>
                    <div class="r f-l" bk="life_right">
                      {qcms_block id="210512439" dtid="490687946" count="1" width="180" height="194" qcms-custom-preview="1"} {qcms_block id="210512439" dtid="490687952" count="2" width="180" height="100" qcms-custom-preview="1"}
                      {qcms_block id="210512439" dtid="210512891" count="1" width="180" height="68" qcms-custom-preview="1"}
                    </div>
                  </div>
                  <div class="spage-2" bk="mini_life_page2" data-target="life_page2">
                    <div class="news-container">
                      <ul class="news-content-wrapper">
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="newsflow-tips">
              <img src="http://p7.qhimg.com/d/inn/9f3465b4/odot.png" class="odot"> 更多未读资讯
              <img src="http://p6.qhimg.com/d/inn/9ca1c978/arrow.gif" width="12" height="19">
              <i></i>
            </div>
          </div>
        </div>
        <div class="page" id="tab_shop" bk="mini_shop">
          <iframe src="" frameborder="0" width="750" height="512" scrolling="no" tempsrc="http://pages-juxiao.mediav.com/ad/mini/showcase-750x512-1.html?rec_showid=wl4rc9&def_rec_showid=sisw6L&key_showid=HYkLou&disable_choice=true&disable_lgicon=true&disable_animation=true" hoversrc="http://pages-juxiao.mediav.com/ad/mini/showcase-750x512-1.html?rec_showid=wl4rc9&def_rec_showid=sisw6L&key_showid=HYkLou&disable_choice=true&disable_lgicon=true&is_ready=true"></iframe>
        </div>
        <div class="page" id="tab_finance" bk="mini_finance">
          <div class="page-scrollbar">
            <div class="page_home"></div>
            <div class="scrollbar">
              <div class="track">
                <div class="thumb">
                  <div class="end"></div>
                </div>
              </div>
            </div>
            <div class="viewport">
              <div class="overview">
                <div class="spages">
                  <div class="spage-1" bk="mini_finance_page1">
                    <div class="l f-l">
                      {qcms_block id="210512439" dtid="490687959" count="1" width="180" height="194" qcms-custom-preview="1"} {qcms_block id="210512439" dtid="490687965" count="2" width="180" height="100" qcms-custom-preview="1"}
                      {qcms_block id="210512439" dtid="490919749" count="1" width="180" height="68" qcms-custom-preview="1"}
                    </div>
                    <div class="m f-l">
                      <div class="news">
                        <div class="news-top">
                          {qcms_block id="210512626" dtid="490687969" count="1" qcms-custom-preview="1"} {qcms_block id="490919637" dtid="490687975" count="6" qcms-custom-preview="1"}
                        </div>
                        <div>
                          {qcms_block id="210512626" dtid="490687979" count="1" qcms-custom-preview="1"} {qcms_block id="490919637" dtid="490687983" count="3" qcms-custom-preview="1"}
                        </div>
                        <div>
                          {qcms_block id="210512626" dtid="490687990" count="1" qcms-custom-preview="1"} {qcms_block id="490919637" dtid="490687998" count="5" qcms-custom-preview="1"}
                        </div>
                      </div>
                    </div>
                    <div class="r f-l" bk="finance_right">
                      {qcms_block id="210512439" dtid="490688003" count="1" width="180" height="194" qcms-custom-preview="1"} {qcms_block id="210512439" dtid="490688007" count="2" width="180" height="100" qcms-custom-preview="1"}
                      {qcms_block id="210512439" dtid="210512880" count="1" width="180" height="68" qcms-custom-preview="1"}
                    </div>
                  </div>
                  <div class="spage-2" bk="mini_finance_page2" data-target="finance_page2">
                    <div class="news-container">
                      <ul class="news-content-wrapper">
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="newsflow-tips">
              <img src="http://p7.qhimg.com/d/inn/9f3465b4/odot.png" class="odot"> 更多未读资讯
              <img src="http://p6.qhimg.com/d/inn/9ca1c978/arrow.gif" width="12" height="19">
              <i></i>
            </div>
          </div>
        </div>
        <div class="page" id="tab_tec" bk="mini_tec">
          <div class="page-scrollbar">
            <div class="page_home"></div>
            <div class="scrollbar">
              <div class="track">
                <div class="thumb">
                  <div class="end"></div>
                </div>
              </div>
            </div>
            <div class="viewport">
              <div class="overview">
                <div class="spages">
                  <div class="spage-1" bk="mini_tec_page1">
                    <div class="l f-l">
                      {qcms_block id="210512439" dtid="490688011" count="1" width="180" height="194" qcms-custom-preview="1"} {qcms_block id="210512439" dtid="490688017" count="2" width="180" height="100" qcms-custom-preview="1"}
                      {qcms_block id="210512439" dtid="490919757" count="1" width="180" height="68" qcms-custom-preview="1"}
                    </div>
                    <div class="m f-l">
                      <div class="news">
                        <div class="news-top">
                          {qcms_block id="210512626" dtid="490688023" count="1" qcms-custom-preview="1"} {qcms_block id="490919637" dtid="490688029" count="6" qcms-custom-preview="1"}
                        </div>
                        <div>
                          {qcms_block id="210512626" dtid="490688033" count="1" qcms-custom-preview="1"} {qcms_block id="490919637" dtid="490688038" count="3" qcms-custom-preview="1"}
                        </div>
                        <div>
                          {qcms_block id="210512626" dtid="490688045" count="1" qcms-custom-preview="1"} {qcms_block id="490919637" dtid="490688049" count="5" qcms-custom-preview="1"}
                        </div>
                      </div>
                    </div>
                    <div class="r f-l" bk="tec_right">
                    <!-- <div class="r f-l showcase-placeholder" bk="tec_right" data-showcase=".showcase-1"> -->
                      {qcms_block id="210512439" dtid="490688064" count="1" width="180" height="194" qcms-custom-preview="1"} {qcms_block id="210512439" dtid="490688069" count="2" width="180" height="100" qcms-custom-preview="1"}
                      {qcms_block id="210512439" dtid="490919983" count="1" width="180" height="68" qcms-custom-preview="1"}
                    </div>
                  </div>
                  <div class="spage-2" bk="mini_tec_page2" data-target="tec_page2">
                    <div class="news-container">
                      <ul class="news-content-wrapper">
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="newsflow-tips">
              <img src="http://p7.qhimg.com/d/inn/9f3465b4/odot.png" class="odot"> 更多未读资讯
              <img src="http://p6.qhimg.com/d/inn/9ca1c978/arrow.gif" width="12" height="19">
              <i></i>
            </div>
          </div>
        </div>
        <div class="page" id="tab_sports" bk="mini_sports">
          <div class="page-scrollbar">
            <div class="page_home"></div>
            <div class="scrollbar">
              <div class="track">
                <div class="thumb">
                  <div class="end"></div>
                </div>
              </div>
            </div>
            <div class="viewport">
              <div class="overview">
                <div class="spages">
                  <div class="spage-1" bk="mini_sports_page1">
                    <div class="l f-l">
                      {qcms_block id="210512439" dtid="210390761" count="1" width="180" height="194" qcms-custom-preview="1"} {qcms_block id="210512439" dtid="210390766" count="2" width="180" height="100" qcms-custom-preview="1"}
                      {qcms_block id="210512439" dtid="490919751" count="1" width="180" height="68" qcms-custom-preview="1"}
                    </div>
                    <div class="m f-l">
                      <div class="news">
                        <div class="news-top">
                          {qcms_block id="210512626" dtid="210390770" count="1" qcms-custom-preview="1"} {qcms_block id="490919637" dtid="210390776" count="6" qcms-custom-preview="1"}
                        </div>
                        <div>
                          {qcms_block id="210512626" dtid="210390782" count="1" qcms-custom-preview="1"} {qcms_block id="490919637" dtid="210390787" count="3" qcms-custom-preview="1"}
                        </div>
                        <div>
                          {qcms_block id="210512626" dtid="210390791" count="1" qcms-custom-preview="1"} {qcms_block id="490919637" dtid="210390797" count="5" qcms-custom-preview="1"}
                        </div>
                      </div>
                    </div>
                    <div class="r f-l" bk="sports_right">
                      {qcms_block id="210512439" dtid="210390801" count="1" width="180" height="194" qcms-custom-preview="1"} {qcms_block id="210512439" dtid="210390808" count="2" width="180" height="100" qcms-custom-preview="1"}
                      {qcms_block id="210512439" dtid="210512882" count="1" width="180" height="68" qcms-custom-preview="1"}
                    </div>
                  </div>
                  <div class="spage-2" bk="mini_sports_page2" data-target="sports_page2">
                    <div class="news-container">
                      <ul class="news-content-wrapper">
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="newsflow-tips">
              <img src="http://p7.qhimg.com/d/inn/9f3465b4/odot.png" class="odot"> 更多未读资讯
              <img src="http://p6.qhimg.com/d/inn/9ca1c978/arrow.gif" width="12" height="19">
              <i></i>
            </div>
          </div>
        </div>
        <div class="page" id="tab_car" bk="mini_car">
          <div class="page-scrollbar">
            <div class="page_home"></div>
            <div class="scrollbar">
              <div class="track">
                <div class="thumb">
                  <div class="end"></div>
                </div>
              </div>
            </div>
            <div class="viewport">
              <div class="overview">
                <div class="spages">
                  <div class="spage-1" bk="mini_car_page1">
                    <div class="l f-l">
                      {qcms_block id="210512439" dtid="210390812" count="1" width="180" height="194" qcms-custom-preview="1"} {qcms_block id="210512439" dtid="210390818" count="2" width="180" height="100" qcms-custom-preview="1"}
                      {qcms_block id="210512439" dtid="490919747" count="1" width="180" height="68" qcms-custom-preview="1"}
                    </div>
                    <div class="m f-l">
                      <div class="news">
                        <div class="news-top">
                          {qcms_block id="210512626" dtid="210390822" count="1" qcms-custom-preview="1"} {qcms_block id="490919637" dtid="210390826" count="6" qcms-custom-preview="1"}
                        </div>
                        <div>
                          {qcms_block id="210512626" dtid="490688106" count="1" qcms-custom-preview="1"} {qcms_block id="490919637" dtid="490688112" count="3" qcms-custom-preview="1"}
                        </div>
                        <div>
                          {qcms_block id="210512626" dtid="490688120" count="1" qcms-custom-preview="1"} {qcms_block id="490919637" dtid="490688124" count="5" qcms-custom-preview="1"}
                        </div>
                      </div>
                    </div>
                    <div class="r f-l" bk="car_right">
                      {qcms_block id="210512439" dtid="490688129" count="1" width="180" height="194" qcms-custom-preview="1"} {qcms_block id="210512439" dtid="490688143" count="2" width="180" height="100" qcms-custom-preview="1"}
                      {qcms_block id="210512439" dtid="210512878" count="1" width="180" height="68" qcms-custom-preview="1"}
                    </div>
                  </div>
                  <div class="spage-2" bk="mini_car_page2" data-target="car_page2">
                    <div class="news-container">
                      <ul class="news-content-wrapper">
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="newsflow-tips">
              <img src="http://p7.qhimg.com/d/inn/9f3465b4/odot.png" class="odot"> 更多未读资讯
              <img src="http://p6.qhimg.com/d/inn/9ca1c978/arrow.gif" width="12" height="19">
              <i></i>
            </div>
          </div>
        </div>
        <div class="page" id="tab_constellation" bk="mini_constellation">
          <div class="page-scrollbar">
            <div class="page_home"></div>
            <div class="scrollbar">
              <div class="track">
                <div class="thumb">
                  <div class="end"></div>
                </div>
              </div>
            </div>
            <div class="viewport">
              <div class="overview">
                <div class="spages">
                  <div class="spage-1" bk="mini_constellation_page1">
                    <div class="l f-l">
                      {qcms_block id="210512439" dtid="490688156" count="1" width="180" height="194" qcms-custom-preview="1"} {qcms_block id="210512439" dtid="490688167" count="2" width="180" height="100" qcms-custom-preview="1"}
                      {qcms_block id="210512439" dtid="490919755" count="1" width="180" height="68" qcms-custom-preview="1"}
                    </div>
                    <div class="m f-l">
                      <div class="news">
                        <div class="news-top">
                          {qcms_block id="210512626" dtid="490688178" count="1" qcms-custom-preview="1"} {qcms_block id="490919637" dtid="490688184" count="6" qcms-custom-preview="1"}
                        </div>
                        <div>
                          {qcms_block id="210512626" dtid="490688195" count="1" qcms-custom-preview="1"} {qcms_block id="490919637" dtid="490688201" count="3" qcms-custom-preview="1"}
                        </div>
                        <div>
                          {qcms_block id="210512626" dtid="490688215" count="1" qcms-custom-preview="1"} {qcms_block id="490919637" dtid="490688224" count="5" qcms-custom-preview="1"}
                        </div>
                      </div>
                    </div>
                    <div class="r f-l" bk="constellation_right">
                      {qcms_block id="210512439" dtid="490688230" count="1" width="180" height="194" qcms-custom-preview="1"} {qcms_block id="210512439" dtid="490688242" count="2" width="180" height="100" qcms-custom-preview="1"}
                      {qcms_block id="210512439" dtid="210512886" count="1" width="180" height="68" qcms-custom-preview="1"}
                    </div>
                  </div>
                  <div class="spage-2" bk="mini_constellation_page2" data-target="constellation_page2">
                    <div class="news-container">
                      <ul class="news-content-wrapper">
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="newsflow-tips">
              <img src="http://p7.qhimg.com/d/inn/9f3465b4/odot.png" class="odot"> 更多未读资讯
              <img src="http://p6.qhimg.com/d/inn/9ca1c978/arrow.gif" width="12" height="19">
              <i></i>
            </div>
          </div>
        </div>
        <div class="page" id="tab_digital" bk="mini_digital">
          <div class="page-scrollbar">
            <div class="page_home"></div>
            <div class="scrollbar">
              <div class="track">
                <div class="thumb">
                  <div class="end"></div>
                </div>
              </div>
            </div>
            <div class="viewport">
              <div class="overview">
                <div class="spages">
                  <div class="spage-1" bk="mini_digital_page1">
                    <div class="l f-l">
                      {qcms_block id="210512439" dtid="210390876" count="1" width="180" height="194" qcms-custom-preview="1"} {qcms_block id="210512439" dtid="210390880" count="2" width="180" height="100" qcms-custom-preview="1"}
                      {qcms_block id="210512439" dtid="490919759" count="1" width="180" height="68" qcms-custom-preview="1"}
                    </div>
                    <div class="m f-l">
                      <div class="news">
                        <div class="news-top">
                          {qcms_block id="210512626" dtid="210390884" count="1" qcms-custom-preview="1"} {qcms_block id="490919637" dtid="210390889" count="6" qcms-custom-preview="1"}
                        </div>
                        <div>
                          {qcms_block id="210512626" dtid="210390894" count="1" qcms-custom-preview="1"} {qcms_block id="490919637" dtid="490688336" count="3" qcms-custom-preview="1"}
                        </div>
                        <div>
                          {qcms_block id="210512626" dtid="490688340" count="1" qcms-custom-preview="1"} {qcms_block id="490919637" dtid="490688346" count="5" qcms-custom-preview="1"}
                        </div>
                      </div>
                    </div>
                    <div class="r f-l" bk="digital_right">
                      {qcms_block id="210512439" dtid="490688362" count="1" width="180" height="194" qcms-custom-preview="1"} {qcms_block id="210512439" dtid="490688368" count="2" width="180" height="100" qcms-custom-preview="1"}
                      {qcms_block id="210512439" dtid="210512888" count="1" width="180" height="68" qcms-custom-preview="1"}
                    </div>
                  </div>
                  <div class="spage-2" bk="mini_digital_page2" data-target="digital_page2">
                    <div class="news-container">
                      <ul class="news-content-wrapper">
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="newsflow-tips">
              <img src="http://p7.qhimg.com/d/inn/9f3465b4/odot.png" class="odot"> 更多未读资讯
              <img src="http://p6.qhimg.com/d/inn/9ca1c978/arrow.gif" width="12" height="19">
              <i></i>
            </div>
          </div>
        </div>
        <div class="page" id="tab_fashion" bk="mini_fashion">
          <div class="page-scrollbar">
            <div class="page_home"></div>
            <div class="scrollbar">
              <div class="track">
                <div class="thumb">
                  <div class="end"></div>
                </div>
              </div>
            </div>
            <div class="viewport">
              <div class="overview">
                <div class="spages">
                  <div class="spage-1" bk="mini_fashion_page1">
                    <div class="l f-l">
                      {qcms_block id="210512439" dtid="490688376" count="1" width="180" height="194" qcms-custom-preview="1"} {qcms_block id="210512439" dtid="490688382" count="2" width="180" height="100" qcms-custom-preview="1"}
                      {qcms_block id="210512439" dtid="490919763" count="1" width="180" height="68" qcms-custom-preview="1"}
                    </div>
                    <div class="m f-l">
                      <div class="news">
                        <div class="news-top">
                          {qcms_block id="210512626" dtid="490688386" count="1" qcms-custom-preview="1"} {qcms_block id="490919637" dtid="490688390" count="6" qcms-custom-preview="1"}
                        </div>
                        <div>
                          {qcms_block id="210512626" dtid="490688394" count="1" qcms-custom-preview="1"} {qcms_block id="490919637" dtid="490688408" count="3" qcms-custom-preview="1"}
                        </div>
                        <div>
                          {qcms_block id="210512626" dtid="490688416" count="1" qcms-custom-preview="1"} {qcms_block id="490919637" dtid="490688426" count="5" qcms-custom-preview="1"}
                        </div>
                      </div>
                    </div>
                    <div class="r f-l" bk="fashion_right">
                      {qcms_block id="210512439" dtid="490688433" count="1" width="180" height="194" qcms-custom-preview="1"} {qcms_block id="210512439" dtid="490688448" count="2" width="180" height="100" qcms-custom-preview="1"}
                      {qcms_block id="210512439" dtid="210512894" count="1" width="180" height="68" qcms-custom-preview="1"}
                    </div>
                  </div>
                  <div class="spage-2" bk="mini_fashion_page2" data-target="fashion_page2">
                    <div class="news-container">
                      <ul class="news-content-wrapper">
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="newsflow-tips">
              <img src="http://p7.qhimg.com/d/inn/9f3465b4/odot.png" class="odot"> 更多未读资讯
              <img src="http://p6.qhimg.com/d/inn/9ca1c978/arrow.gif" width="12" height="19">
              <i></i>
            </div>
          </div>
        </div>
        <div class="page" id="tab_culture" bk="mini_culture">
          <div class="page-scrollbar">
            <div class="page_home"></div>
            <div class="scrollbar">
              <div class="track">
                <div class="thumb">
                  <div class="end"></div>
                </div>
              </div>
            </div>
            <div class="viewport">
              <div class="overview">
                <div class="spages">
                  <div class="spage-1" bk="mini_culture_page1">
                    <div class="l f-l">
                      {qcms_block id="210512439" dtid="490688454" count="1" width="180" height="194" qcms-custom-preview="1"} {qcms_block id="210512439" dtid="490688461" count="2" width="180" height="100" qcms-custom-preview="1"}
                      {qcms_block id="210512439" dtid="490919767" count="1" width="180" height="68" qcms-custom-preview="1"}
                    </div>
                    <div class="m f-l">
                      <div class="news">
                        <div class="news-top">
                          {qcms_block id="210512626" dtid="490688467" count="1" qcms-custom-preview="1"} {qcms_block id="490919637" dtid="490688474" count="6" qcms-custom-preview="1"}
                        </div>
                        <div>
                          {qcms_block id="210512626" dtid="490688478" count="1" qcms-custom-preview="1"} {qcms_block id="490919637" dtid="490688482" count="3" qcms-custom-preview="1"}
                        </div>
                        <div>
                          {qcms_block id="210512626" dtid="490688487" count="1" qcms-custom-preview="1"} {qcms_block id="490919637" dtid="490688497" count="5" qcms-custom-preview="1"}
                        </div>
                      </div>
                    </div>
                    <div class="r f-l" bk="culture_right">
                      {qcms_block id="210512439" dtid="490688502" count="1" width="180" height="194" qcms-custom-preview="1"} {qcms_block id="210512439" dtid="490688506" count="2" width="180" height="100" qcms-custom-preview="1"}
                      {qcms_block id="210512439" dtid="210512897" count="1" width="180" height="68" qcms-custom-preview="1"}
                    </div>
                  </div>
                  <div class="spage-2" bk="mini_culture_page2" data-target="culture_page2">
                    <div class="news-container">
                      <ul class="news-content-wrapper">
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="newsflow-tips">
              <img src="http://p7.qhimg.com/d/inn/9f3465b4/odot.png" class="odot"> 更多未读资讯
              <img src="http://p6.qhimg.com/d/inn/9ca1c978/arrow.gif" width="12" height="19">
              <i></i>
            </div>
          </div>
        </div>
        <!-- <div class="page" id="tab_lianmeng" bk="mini_lianmeng">
          <iframe src="" frameborder="0" width="708" height="418" scrolling="no" tempsrc="http://api.so.lianmeng.360.cn/pmini"></iframe>
        </div> -->
        <div class="showcase showcase-1" bk="mini_showcase">
          <div class="top">
            <div class="box item item-first">
              <p class="img-ad is-ads"></p>
              <a class="ad-link" href=":;">
                <img src="" alt="" width="178" height="178">
                <p class="item-title"></p>
                <div class="tag tag-cheap">优选</div>
              </a>
            </div>
            <div class="item-list">
              <ul></ul>
              <div bk="showcase-arrow-pre" class="arrow-left">
                <div class="arrow-ico">&nbsp;&nbsp;</div>
              </div>
              <div bk="showcase-arrow-next" class="arrow-right">
                <div class="arrow-ico">&nbsp;&nbsp;</div>
              </div>
            </div>
          </div>
          <div class="bottom">
            <div class="box item item-second">
              <p class="img-ad is-ads"></p>
              <a class="ad-link" href=":;">
                <img src="" alt="" width="178" height="178">
                <p class="item-title"></p>
                <div class="tag tag-fresh">推荐</div>
              </a>
            </div>
          </div>
        </div>
        <div class="showcase showcase-2" bk="mini_showcase2">
          <div class="top">
            <div class="box item item-first">
              <p class="img-ad is-ads"></p>
              <a class="ad-link" href=":;">
                <img src="" alt="" width="178" height="178">
                <p class="item-title"></p>
              </a>
            </div>
            <div class="item-list">
              <ul></ul>
              <div bk="showcase-arrow-pre" class="arrow-left">
                <div class="arrow-ico">&nbsp;&nbsp;</div>
              </div>
              <div bk="showcase-arrow-next" class="arrow-right">
                <div class="arrow-ico">&nbsp;&nbsp;</div>
              </div>
            </div>
          </div>
          <div class="bottom">
            <div class="box item item-second">
              <p class="img-ad is-ads"></p>
              <a class="ad-link" href=":;">
                <img src="" alt="" width="178" height="178">
                <p class="item-title"></p>
              </a>
            </div>
          </div>
        </div>
      </div>
      <a href="//sh.qihoo.com/pc/?sign=ex_40895b4c" class="technical">内容由快资讯提供，查看更多></a>
    </div>
    {qcms_block id="490964793" dtid="490688641" count="1" qcms-custom-preview="1"}
  </div>
  <script type="text/template" id="tpl-news-news">
    <li {{? it.adsId}}id="{{=it.adsId}}" {{?}}class="news-pack clearfix {{= it.packType}} {{= it.firstItem}} {{= it.firstItem}}-{{= it.packType}}" data-newsType="{{=it.newsType}}">
      <a class="news-link clearfix" data-clicktk="{{=it.clicktk}}" data-imptk="{{=it.imptk}}" data-u="{{=it.u}}" data-c="{{=it.c}}" data-a="{{=it.a}}" data-log="{{=it.log}}" data-source="{{=it.source}}" data-newstype="{{= it.newsType}}" href="{{=it.pcurl}}" target="_blank">
      {{? it.packType == 'news-tpl2'}}
      <div class="news-imgs">
        {{~ it.imgUrl :p:k }}
        <span class="news-img-a{{? it.newsType == 'ads'}} news-ads-a{{?}}">
              <img class="news-img" src="{{=p}}" onerror="src='http://p0.qhimg.com/t01c8d837ba85a8eeb2.png'">
                {{? it.isVideo }}
                  <span class="news-img-duration">
                    {{=it.duration}}
                  </span>
                {{?}}
            </span>
        {{~}}
      </div>
      <div class="news-content">
        {{?}}
        <h2 class="news-h2">
          <span title="{{!it.title}}" class="news-title{{? it.newsType == 'ads'}} news-ads-a{{?}}">{{=it.t}}</span>
        </h2>
        {{? it.packType == 'news-tpl3'}}
        <div class="news-imgs clearfix">
          {{~ it.imgUrl :m:n }}
          <span class="news-img-a{{? it.newsType == 'ads'}} news-ads-a{{?}}">
                <img class="news-img" src="{{=m}}" onerror="src='http://p0.qhimg.com/t01c8d837ba85a8eeb2.png'">
                {{? it.isVideo }}
                  <span class="news-img-duration">
                    {{=it.duration}}
                  </span>
                {{?}}
              </span>
          {{~}}
        </div>
        {{?}}
        <div class="news-info {{? it.desc}}news-info-ads{{?}}">
          {{? it.a}}
          <span class="news-tag{{? it.a === 'h'}} news-tag-hide{{?}}">
                {{? it.a == 'g'}} 热 {{?}} {{? it.a == 'l'}} 荐 {{?}} {{? it.a == 't'}} 顶 {{?}} {{? it.a == 'a'}} 推 {{?}}
              </span>
          {{?}} {{? it.newsType == 'ads'}}
          <span class="ads-tag"></span>
          {{?}}
          <span class="news-from">{{=it.f || ''}}</span>
          {{? it.newsType == 'ads'}}
          <span class="ads-tag">广告</span>
          {{?}}
          <span class="news-date">{{=it.newsTime || ''}}</span>
        </div>
        {{? it.packType == 'news-tpl2'}}
      </div>
      <div class="clearfix"></div>
      {{?}}
    </a>
      <!-- {{? it.newsType != 'ads'}}<span class="news-dislike" data-log={{=it.s_log}}>&nbsp;&nbsp;不感兴趣</span>{{?}} -->
    </li>
  </script>
  <script type="text/template" id="tpl-news-ads2">
    <li {{? it.adsId}}id="{{=it.adsId}}" {{?}} class="news-pack {{= it.packType}} {{= it.firstItem}}">
      <div class="news-ads2-hd">
        <a class="news-title news-ads-a" href="{{=it.pcurl}}" data-clicktk="{{=it.clicktk}}" data-newstype="{{= it.newsType}}" target="_blank">{{=it.t}}</a>
      </div>
      <div class="news-ads2-bd">
        {{~ it.data :m:n}}
        <a class="news-ads-a news-ads2-link" href="{{=m.curl}}" data-clicktk="{{=it.clicktk}}" data-newstype="{{= it.newsType}}" target="_blank">
          <img class="news-ads2-img" src="{{=m.img}}">
        </a> {{~}}
      </div>
      <div class="news-info">
        <span class="news-from">{{=it.f}}</span>
        <span class="ads-tag">广告</span>
      </div>
    </li>
  </script>
  <script type="text/template" id="tpl-video-360kan">
    <li {{? it.adsId}}id="{{=it.adsId}}" class="show-iad" {{?}}>
      <div class="pic_box2" bosszone="video_page2_pic1">
        <a target="_blank" href="{{=it.url||it.pcurl}}" title="{{=it.title}}" data-newstype="{{= it.newsType||''}}" data-clicktk="{{=it.clicktk||''}}">
          <div class="pic">
            <img src="{{=it.img||it.imgUrl[0]}}">
          </div>
          <div class="txt">
            <div class="tit">
              <span class="fl">{{=StringH.subByte(it.title, 44)}}</span>
            </div>
          </div>
          <span class="ico_playb"></span>
          <span class="ico_ad"></span>
        </a>
      </div>
    </li>
  </script>
  <script type="text/template" id="tpl-video-360browser">
    <li {{? it.adsId}}id="{{=it.adsId}}" class="show-iad" {{?}}>
      <div class="pic_box2" data-target="{{= it.pid||''}}">
        <a href="{{=it.link}}" title="{{!it.title}}" data-newstype="{{= it.newsType||''}}" data-clicktk="{{=it.clicktk||''}}" data-log="{{=it.log||''}}" ctype="{{= it.newsType == 'ads' ? 1 : 0 }}" {{? it.slog}} data-a="{{= it.slog.a}}" data-sid="{{= it.slog.sid}}" data-c="{{= it.slog.c}}" data-s="{{= it.slog.s}}" data-source="{{= it.slog.source}}" data-channel="{{= it.slog.channel}}" {{?}}>
          <div class="pic">
            <img src="{{=it.img}}">
          </div>
          <div class="txt">
            <div class="tit">
              <span class="fl">{{=StringH.subByte(it.title, 44)}}</span>
            </div>
          </div>
          <span class="{{= it.newsType=='video' ? 'ico_playb':'ico_news' }}"></span>
          <span class="ico_ad"></span>
        </a>
      </div>
    </li>
  </script>
  <!--引入打点代码-->
  <script src="//s0.ssl.qhres.com/static/2afc71670295f3b8/jquery,qw.core.js"></script>
  <script src="//s1.ssl.qhres.com/static/ab69bff62405ffb7/utils.js"></script>
  <script src="//s2.ssl.qhres.com/!12d69278/doT.js"></script>
  <script src="//s3.ssl.qhres.com/!72af2cbf/md5.js"></script>
  <script src="//s4.ssl.qhres.com/static/98c707edc784aedb/monitor.js"></script>
  {qcms_script id="210536948" name="jquery.tinyscrollbar"} {qcms_script id="490964807" name="q.js"}
  <script>
  $.ajax({
    url: '/config/time_range.json.html',
    // 随机数慎用，防CND穿透
    data: {
      _: Math.floor(new Date().getTime() / 1000 / 60 / .5)
    },
    dataType: 'JSON',
    // cache: false,
    success: function(res, status, xhr) {
      var serverTime = new Date(xhr.getResponseHeader('Date'));
      for (var i = 0; i < res.length; i++) {
        var startTime = new Date(res[i].start.replace(/-/g, '/'));
        var endTime = new Date(res[i].end.replace(/-/g, '/'));
        if (serverTime >= startTime && serverTime < endTime) {
          location.href = 'http://pages-juxiao.mediav.com/ad/mini/showcase-750x492-1.html?rec_showid=0LAEBY&def_rec_showid=0LAEBY&key_showid=CcYjAw&disable_choice=true&disable_lgicon=true&is_ready=true';
          break;
        }
      }
    }
  });
  </script>
  <script>
  var mv_uid = (function() {
    function getHash(str) {
      var hash = 1,
        charCode = 0,
        idx;
      if (str) {
        hash = 0;
        for (idx = str.length - 1; idx >= 0; idx--) {
          charCode = str.charCodeAt(idx);
          hash = (hash << 6 & 268435455) + charCode + (charCode << 14);
          charCode = hash & 266338304;
          hash = charCode != 0 ? hash ^ charCode >> 21 : hash;
        }
      }
      return hash;
    }

    return ("" + getHash(window.location.href) + getHash(document.domain) + (new Date() - 0) + Math.floor(Math.random() * 1000)).substr(0, 32);
  })();
  var isIE = !!window.ActiveXObject;
  var isIE6 = isIE && !window.XMLHttpRequest;
  var Cookie = {
    get: function(key) {
      try {
        var doc = document,
          a, reg = new RegExp("(^| )" + key + "=([^;]*)(;|$)");
        if (a = doc.cookie.match(reg)) {
          return unescape(a[2]);
        } else {
          return "";
        }
      } catch (e) {
        return "";
      }
    },
    set: function(key, val, options) {
      options = options || {};
      var expires = options.expires;
      var doc = document;
      if (typeof(expires) === "number") {
        expires = new Date();
        expires.setTime(expires.getTime() + options.expires);
      }

      try {
        doc.cookie =
          key + "=" + escape(val) + (expires ? ";expires=" + expires.toGMTString() : "") + (options.path ? ";path=" + options.path : "") + (options.domain ? "; domain=" + options.domain : "");
      } catch (e) {}
    }
  };

  window.mid = '';
  var version = '';
  try {
    version = external.GetVersion();
    mid = external.GetMID();
  } catch (err) {
    mid = Cookie.get('_t_mid');
    if (!mid) {
      mid = hex_md5(Math.random().toString());
      Cookie.set('_t_mid', mid, {
        expires: 1000 * 60 * 60 * 24 * 365
      });
    }
  }
  var isNewVersion = version >= '9.1.0.100';
  </script>
  <script>
  var jumbotronInited = false;
  var from = /from=pmp/.test(location.search);

  function Jumbotron() {
    this.delayTimer = null;
    this.playTimer = null;
    this.jumbotronShowed = false;
    this.REORD_KEY = 'jumbotron_date';
    this.DELAY_TIMEOUT = (isNewVersion || from) ? 0 : 1e4;
    this.$container = $('.jumbotron-container');
    this.$timeout = this.$container.find('.btn-timeout');
    this.$replay = $('.btn-replay');
    this.PLAY_TIMEOUT = +(this.$container.attr('data-time') || 3);

    this._bindEvents();
  }

  function dateFormat(date) {
    var year = date.getFullYear();
    var month = date.getMonth();
    var day = date.getDate();
    return [year, month, day].join('_');
  }

  Jumbotron.prototype = {
    needShow: function() {
      var fmt = dateFormat(new Date());
      var val = Cookie.get(this.REORD_KEY);
      return from || (val != fmt);
    },

    isVisible: function() {
      return this.$container.is(':visible');
    },

    _record: function() {
      var fmt = dateFormat(new Date());
      Cookie.set(this.REORD_KEY, fmt, {
        expires: 1000 * 60 * 60 * 24 * 365
      });
    },

    _bindEvents: function() {
      var self = this;

      this.$container.on('click', function() {
        self.stop();
      }).on('click', '.btn-timeout', function(e) {
        e.preventDefault();
        e.stopPropagation();
        self.stop();
        // se_monitor.customizeLog({
        //   event_name: 'click',
        //   para: {
        //     act: 'click',
        //     pid: 'p_jumbotron_skip'
        //   }
        // });
      });

      this.$replay.on('click', function(e) {
        e.preventDefault();
        e.stopPropagation();
        self.play();
        // se_monitor.customizeLog({
        //   event_name: 'click',
        //   para: {
        //     act: 'click',
        //     pid: 'p_jumbotron_replay'
        //   }
        // });
        // mv重播曝光
        new Image().src = $(this).data('acttk');
      });
    },

    _renderTimeout: function(timeout) {
      this.$timeout.text('跳过广告' + timeout + 's');
    },

    setFadeOffset: function(offset) { //offset.bottom , offset.left 设置收起位置属性 liuguanyu,2017-09-11
      this._offset = offset;
    },

    setReplay: function(replay) { //设置replay按钮 liuguanyu,2017-09-12
      this.$replay = replay;
    },

    setShowIds: function(showids) { //设置showids liuguanyu,2017-09-12
      this.showids = showids;
    },

    setPid: function(pid) { //设置pid liuguanyu,2017-09-12
      this.pid = pid;
    },

    getShowIds: function() { //获取showids liuguanyu,2017-09-12
      return this.showids;
    },

    getPid: function() { //获取pid liuguanyu,2017-09-12
      return this.pid;
    },

    play: function() {
      var self = this;

      jumbotronInited = true;
      this.jumbotronShowed = true;

      // if (this.$replay.css('visibility') == 'hidden') {
      //   se_monitor.customizeLog({
      //     event_name: 'track',
      //     para: {
      //       act: 'track',
      //       pid: 'p_jumbotron_replay'
      //     }
      //   });
      //   se_monitor.customizeLog({
      //     event_name: 'track',
      //     para: {
      //       act: 'track',
      //       pid: (self.pid ? self.pid : 'p_jumbotron_small')
      //     }
      //   });
      // }

      this.$replay.css({
        'visibility': 'visible'
      });
      this.$container.css({
        width: '100%',
        height: '290px',
        bottom: '0',
        left: '0',
        opacity: 1
      }).slideDown(function() {
        self._record();
      });

      // se_monitor.customizeLog({
      //   event_name: 'track',
      //   para: {
      //     act: 'track',
      //     pid: 'p_jumbotron'
      //   }
      // });

      // se_monitor.customizeLog({
      //   event_name: 'track',
      //   para: {
      //     act: 'track',
      //     pid: 'p_jumbotron_skip'
      //   }
      // });
      var counter = 0;

      clearInterval(this.playTimer);
      this._renderTimeout(this.PLAY_TIMEOUT - counter);
      this.playTimer = setInterval(function() {
        if (++counter <= self.PLAY_TIMEOUT) {
          self._renderTimeout(self.PLAY_TIMEOUT - counter);
        } else {
          self.stop();
        }
      }, 1e3);
    },

    stop: function() {
      clearTimeout(this.delayTimer);
      clearInterval(this.playTimer);

      var self = this;
      if (this._offset) { // 增加修改收起位置的特性 liuguanyu 2017-09-11
        this.$container.animate({
          width: '0',
          height: '0',
          bottom: this._offset.bottom + 'px',
          left: this._offset.left + 'px',
          opacity: 0
        }, function() {
          jumbotronInited = false;
          self.$container.hide();
        });
      } else {
        this.$container.animate({
          width: '0',
          height: '0',
          bottom: '300px',
          left: '680px',
          opacity: 0
        }, function() {
          jumbotronInited = false;
          self.$container.hide();
        });
      }
    },

    init: function(ad) {
      jumbotronInited = false;
      if (!ad.lcurl || !ad.limg || !this.needShow()) return;
      jumbotronInited = true;

      this.$container.find('.btn-link').attr({
        href: ad.lcurl,
        ctype: 1,
        clktks: ad.clktk.join('|')
      });
      this.$container.find('img').attr({
        src: ad.limg
      });
      this.$replay.data('acttk', ad.acttk);

      var self = this;
      var consumedTime = new Date().getTime() - startTime;

      this.delayTimer = setTimeout(function() {
        var $cur = $('#nav a.cur');
        var bk = $cur.attr('bk');
        if (bk != 'nav_rec') {
          jumbotronInited = false;
        } else {
          self.play();
        }
      }, this.DELAY_TIMEOUT - consumedTime);
    }
  };
  </script>
  <script>
  (function() {
    if (Cookie.get('video-guide-showed') < 1) {
      $('.nav-li-video').addClass('video-guide');
      Cookie.set('video-guide-showed', 1, {
        expires: 1000 * 60 * 60 * 24 * 365 * 100
      });
    }
    // 周末科技与直播换位
    // var $navs = $('#nav li');
    // var week = new Date().getDay();
    // if (week == 0 || week == 6) {
    //   $navs.eq(18).insertAfter($navs.eq(11));
    //   var $navs = $('#nav li');
    //   $navs.eq(11).insertAfter($navs.eq(18));
    // }
  })();
  var morPosIdx = 11;
  var mini = {
    $page: $('.page'),
    $nav: $('#nav'),
    firstCarouselDelay: null,
    pageShowDelay: 300,
    timerId: null,
    $morePosNavLink: $('#nav li').eq(morPosIdx),
    morePosNavLinkHtml: $('#nav li').eq(morPosIdx).html(),

    // dotList: {
    //   img_recommend_pv: 'http://dd.browser.360.cn/static/a/553.8948.gif',
    //   recommend_right_ads_big: 'http://dd.browser.360.cn/static/a/553.791.gif',
    //   recommend_right_ads_small: 'http://dd.browser.360.cn/static/a/553.8606.gif',

    //   img_game_pv: 'http://dd.browser.360.cn/static/a/553.4575.gif',
    //   game_left_ads_big: 'http://dd.browser.360.cn/static/a/553.2210.gif',
    //   game_left_ads_small_1: 'http://dd.browser.360.cn/static/a/553.9136.gif',
    //   game_left_ads_small_2: 'http://dd.browser.360.cn/static/a/553.1065.gif',

    //   game_right_ads_big: 'http://dd.browser.360.cn/static/a/553.5009.gif',
    //   game_right_ads_small: 'http://dd.browser.360.cn/static/a/553.2380.gif',

    //   game_text_top: 'http://dd.browser.360.cn/static/a/553.9868.gif',
    //   game_text_center: 'http://dd.browser.360.cn/static/a/553.1670.gif',
    //   game_text_bottom: 'http://dd.browser.360.cn/static/a/553.7895.gif'
    // },
    dotting: function(url) {
      new Image().src = [url, '?_', Math.random()].join('');
    },
    hoverPageAction: function($channel, iftrack) {
      if ($channel.text() === '推荐') {
        $('.technical').css('bottom', window.recommend_technical_bottom || '-9px');
      } else {
        $('.technical').css('bottom', '-9px');
      }
      jumbotron.stop();
      clearTimeout(mini.firstCarouselDelay);
      if (!$channel.parent().is(':visible')) {
        return;
      }
      var self = this;
      self.$page.hide();
      self.$nav.find('a').removeClass('cur');
      $channel.addClass('cur');

      var pid = $channel.attr('id')
      var cate = pid.slice(4);
      var $tarcon = $('#tab_' + cate);
      self.loadPageImages($tarcon);


      showcaseVisible = false;
      if (showcaseValid) {
        $('.showcase').css('visibility', 'hidden');
        var $placeholder = $tarcon.find('.showcase-placeholder');
        if ($placeholder.length > 0) {
          showcaseVisible = true;
          var showcaseSelector = $placeholder.data('showcase');
          $(showcaseSelector).css('visibility', 'visible');
          $('body').trigger('showcaseVisible' + showcaseSelector.replace('.', '-'));
        }
      }


      if ($tarcon.find('iframe').length && $tarcon.find('iframe').attr('src') == '') {
        var tempsrc = $tarcon.find('iframe').attr('tempsrc').replace('{mid}', mid);
        $tarcon.find('iframe').attr('src', tempsrc);
      }
      if (iftrack && $tarcon.find('iframe').length) {
        var hoversrc = $tarcon.find('iframe').attr('hoversrc'); 
        var tempsrc = $tarcon.find('iframe').attr('src');
        if (hoversrc && $tarcon.find('iframe').attr('hascached') !== '0') {
          $tarcon.find('iframe').attr('hascached', '0');
          $tarcon.find('iframe').attr('src', hoversrc);
        }
        if (tempsrc.indexOf('://api.so.lianmeng.360.cn/pmini') > -1) {
          $tarcon.find('iframe').attr('src', tempsrc.replace('?is_hover=1', '') + '?is_hover=1');
        }
      }

      $tarcon.show();

      var tinyscrollbar = $tarcon.find('.page-scrollbar').data('plugin_tinyscrollbar');
      if (tinyscrollbar) {
        if (isNaN(tinyscrollbar.contentRatio)) {
          tinyscrollbar.update();
        }
      }

      if (cate != 'shop' && cate != 'anecdote' && cate != 'lianmeng') {
        $('.technical').show();
      } else {
        $('.technical').hide();
      }

      // (cate == 'rec') && self.dotting(self.dotList['img_recommend_pv']);
      // (cate == 'game') && self.dotting(self.dotList['img_game_pv']);

      if (iftrack) {
        if (cate == 'video') {
          $('.video-guide').removeClass('video-guide');
        }
        // se_monitor.customizeLog({
        //   event_name: 'track',
        //   para: {
        //     act: 'track',
        //     pid: 'p_' + pid
        //   }
        // });
        if (window.QIHOO_MONITOR_BAODIAN) {
          QIHOO_MONITOR_BAODIAN.getTrack(null, { cat: $channel.text() });
        }
      }
    },
    loadPageImages: function($page) {
      if ($page.data('images-loaded')) {
        return;
      }
      $page.find('img').each(function() {
        if (!this.src) {
          this.src = $(this).data('src');
        }
      });
      $page.data('images-loaded', true);
    },
    getVideoData: function() {
      var self = this;
      $.ajax({
        url: 'http://k.360kan.com/video/btime/minilist?from=mini&n=12',
        data: {},
        dataType: 'jsonp',
        success: function(res) {
          if (!res.errno) {
            self.drawVideoPage(res.data);
          }
        }
      });
    },

    appendZero: function(obj) {
      if (parseInt(obj) < 10) return "0" + "" + obj;
      else return obj;
    },

    videoTimeHandler: function(time) {
      var self = this;
      var getHours = +(time / 3600) > 1 ? parseInt(time / 3600) + ':' : '';
      var getMin = +(time / 60) > 0 ? parseInt(time / 60) + ':' : '';
      var getSec = +time % 60;

      return (self.appendZero(getHours) + self.appendZero(getMin) + self.appendZero(getSec));
    },

    drawVideoPage: function(videoList) {
      var self = this;
      var len = videoList.length > 12 ? 12 : videoList.length;
      var dom = '';

      for (var i = 0; i < len; i++) {
        var item = videoList[i];
        var videoLen = self.videoTimeHandler(item['duration']);
        var title = '';

        if (item.title.length <= 24) {
          title = item.title;
        } else {
          title = item.title.substring(0, 24) + "...";
        }

        dom += '<li class="video-item">' +
          '<a class="video-poster-wrapper" href="' + item.url + '">' +
          '<img src="' + item.img + '">' +
          '<span class="video-time">' + videoLen + '</span>' +
          '<p class="video-intro"><span>' + title + '</span></p>' +
          '</a>';
      }

      $('#tab_video').html(dom);
      $('#tab_video li:nth-child(4n)').css('margin-right', 0);
    },

    orderFn: function() {
      var self = this;
      var index = 1;
      var count = $('#nav li').length;
      self.timerId = setInterval(function() {
        if (jumbotronInited) return;

        if (index < count && index != morPosIdx) {
          $("#nav li").eq(index).siblings("li").find("a").removeClass("cur");
          var $channel = $("#nav li").eq(index).find("a").addClass("cur");
          mini.hoverPageAction($channel, false);
          //$(".content .page").hide().eq(index).show();
          index++;
        } else if (index == morPosIdx) {
          $("#nav li").eq(index).siblings("li").find("a").removeClass("cur");
          var $channel = $("#nav li").eq(index).find("a").addClass("cur");
          mini.hoverPageAction($channel, false);
          //$(".content .page").hide().eq(index).show();
          $(".nav").animate({
            'top': '-37px'
          }, 300).addClass("top38");
          $(".handover").find("span").html("返回");
          $(".handover").find("i").addClass("rotate").removeClass("rotate-back");
          index++;
        } else if (index == count) {
          //$("#nav li").eq(0).mouseenter();
          var $channel = $("#nav li").eq(0).find('a').addClass("cur");
          mini.hoverPageAction($channel, false);
          $(".nav").animate({
            'top': '1px'
          }, 300).removeClass("top38");
          $(".handover").find("span").html(mini.morePosNavLinkHtml);
          $(".handover").find("i").removeClass("rotate").addClass("rotate-back");
          clearInterval(self.timerId);
        }
      }, 3000)
    },

    stopOrder: function() {
      clearTimeout(mini.firstCarouselDelay);
      clearInterval(mini.timerId);
    }
  };

  $(function() {
    window.jumbotron = new Jumbotron();

    mini.firstCarouselDelay = setTimeout(function() {
      mini.orderFn();
    }, isNewVersion ? 2000 : 12 * 1000);

    // var DOTLIST = mini.dotList;

    mini.loadPageImages($('#tab_rec'));
    $('#tab_rec').show();

    // mini.getVideoData();

    // se_monitor.init({
    //   project: '360se_mini_baodian',
    //   basePar: {
    //     pid: 'p_nav_rec'
    //   },
    //   isOpenClick: false
    // });
    // mini.dotting(DOTLIST['img_recommend_pv']);

    $(document).on('click', function(e) {
      var $target = $(e.target),
        bk = $target.parents('[bk]').attr('bk');

      // if (DOTLIST[bk]) {
      //   mini.dotting(DOTLIST[bk]);
      // }
    });

    $('.wrapper').on('click', 'a', function(e) {
      // var pid = $('#nav').find('.cur').attr('id');
      var href = $(this).attr('href');
      if (!/^(javascript:|#)/i.test(href)) {
        try {
          external.OpenUrl(href);
          e.preventDefault();
        } catch (err) {}
      }
      var $target = $(e.target);
      var pid = $target.parents('[data-target]').length ? $target.parents('[data-target]').data('target') : $('#nav').find('.cur').attr('id');

      var ctype = $target.attr('ctype');
      if (ctype === undefined) {
        ctype = $target.parents('[ctype]').attr('ctype');
      }
      ctype = ctype || 0;

      // se_monitor.customizeLog({
      //   event_name: 'click',
      //   para: {
      //     act: 'click',
      //     pid: 'p_' + pid,
      //     ct: ctype
      //   },
      //   extendOtherData: 'click',
      //   el: e
      // });

    });

    $('#nav').on('mouseenter', 'li', function() {
      clearTimeout(mini.pageShowDelay);
      clearInterval(mini.timerId);

      var $item = $(this).find('a');
      mini.pageShowDelay = setTimeout(function() {
        mini.hoverPageAction($item, true);
      }, 300);
    });

    $('#nav').on('click', 'li', function() {
      clearTimeout(mini.pageShowDelay);

      var $item = $(this).find('a');
      mini.hoverPageAction($item, true);
    });

    $('#nav').on('mouseleave', 'li', function() {
      clearTimeout(mini.pageShowDelay);
    });

    $(".handover").on("mouseenter", function() {
      clearInterval(mini.timerId);

      if ($(".nav").hasClass('top38')) {
        $(".nav").animate({
          'top': '1px'
        }, 300).removeClass("top38");
        $(this).find("span").html(mini.morePosNavLinkHtml);
        $(this).find("i").removeClass("rotate").addClass("rotate-back");
        $("#nav li:first-child()").siblings("li").find("a").removeClass("cur");
        $("#nav li:first-child()").mouseenter().find("a").addClass("cur");
      } else {
        $(".nav").animate({
          'top': '-37px'
        }, 300).addClass("top38");
        $(this).find("span").html("返回");
        $(this).find("i").addClass("rotate").removeClass("rotate-back");
        mini.$morePosNavLink.siblings("li").find("a").removeClass("cur");
        mini.$morePosNavLink.mouseenter().find("a").addClass("cur");
      }
    });

    //返回按钮
    $(".handover").on("click", function() {
      if ($(this).find("span").text() == "返回") {
        $(".nav").animate({
          'top': '1px'
        }, 300).removeClass("top38");
        $(this).find("span").html(mini.morePosNavLinkHtml);
        $(this).find("i").removeClass("rotate").addClass("rotate-back");
        $("#nav li:first-child()").siblings("li").find("a").removeClass("cur");
        $("#nav li:first-child()").mouseenter().find("a").addClass("cur");
      }
    });

    $(document).delegate('a[href!=""]', 'click', function(e) {
      // MV clktk 打点
      var clktks = $(this).attr('clktks');
      if (clktks) {
        clktks.split('|').forEach(function(item) {
          new Image().src = item;
        });
      }
    });


    // function showMediav($container, showids) {
    //   // var $pos = $('[bk=recommend_right_ads_big]');

    //   $container.css({
    //     visibility: 'hidden'
    //   });
    //   // var showids = 'qy8I4Y';

    //   $.ajax({
    //     url: '//show-g.mediav.com/s?type=1&of=4&newf=2',
    //     data: {
    //       showids: showids,
    //       mid: mid
    //     },
    //     dataType: "jsonp",
    //     jsonp: "jsonp",
    //     jsonpCallback: "callback_mediav_" + showids,
    //     timeout: 3000,
    //     success: function(data) {
    //       var impurl = data && data.impurl;
    //       var ads = data && data.adspaces && data.adspaces[showids];
    //       ads = ads && ads.ads && ads.ads[0];

    //       if (ads) {
    //         if (showids == 'qy8I4Y') {
    //           jumbotron.init(ads);
    //         }

    //         $container.find('a').attr({
    //           href: ads.curl,
    //           ctype: 1,
    //           clktks: ads.clktk.join('|')
    //         }).on('click', function(e) {
    //           if (showids == 'qy8I4Y') {
    //             if (jumbotron.jumbotronShowed) {
    //               se_monitor.customizeLog({
    //                 event_name: 'click',
    //                 para: {
    //                   act: 'click',
    //                   pid: 'p_jumbotron_small'
    //                 }
    //               });
    //             } else {
    //               se_monitor.customizeLog({
    //                 event_name: 'click',
    //                 para: {
    //                   act: 'click',
    //                   pid: 'p_recommend_right_ads'
    //                 }
    //               });
    //             }
    //           }
    //         });
    //         $container.find('img').attr({
    //           src: ads.img,
    //           alt: '' //ads.title
    //         });
    //         $container.find('.img-title').hide();
    //         $container.find('p.img-ad').removeClass('not-ads').addClass('is-ads');

    //         // 展现打点
    //         (ads.imptk || []).forEach(function(item) {
    //           new Image().src = item;
    //         });
    //         impurl && (new Image().src = impurl + ads.imparg);
    //         if (showids == 'qy8I4Y') {
    //           if (!jumbotronInited) {
    //             se_monitor.customizeLog({
    //               event_name: 'track',
    //               para: {
    //                 act: 'track',
    //                 pid: 'p_recommend_right_ads'
    //               }
    //             });
    //           }
    //         }
    //       }
    //       setTimeout(function() {
    //         $container.css({
    //           visibility: 'visible'
    //         });
    //       }, 50);
    //     },
    //     error: function(xhr, status) {
    //       $container.css({
    //         visibility: 'visible'
    //       });
    //     }
    //   });
    // }


    //showMediav($('[bk=recommend_right_ads_big]'), 'qy8I4Y');
    //showMediav($('[bk=recommend_right_ads_small]'), 'a0ZVnP');

    /*************************
     * liuguanyu 2017-09-10
     *************************/
    // 是否是广告
    var isValidKaiping = function(data) {
      var impurl = data && data.impurl;
      var showids = data.showids;
      // var ads = data && data.adspaces && data.adspaces[showids];
      var ads = data;
      ads = ads && ads.ads && ads.ads[0];

      if (!ads) return false;

      if (!ads.lcurl || !ads.limg) return false;

      return true;
    };

    // 广告逻辑
    var doAd = function(data) {
      var impurl = data && data.impurl;
      var showids = data.showids;
      var ads = data;
      // var ads = data && data.adspaces && data.adspaces[showids];
      ads = ads && ads.ads && ads.ads[0];

      if (!ads) return; // 没有广告数据，返回

      $('.technical').css('bottom', '7px');
      window.recommend_technical_bottom = '7px';

      var $container = data.$container;

      // 小图高度变高，右下角最小模块隐藏
      $('[bk=recommend_right_ads_small] img').css('height', '180px');
      $('[bk=recommend_right_ads_bottom]').hide();
      $container.find('a').attr({
          href: ads.curl,
          ctype: 1,
          clktks: ads.clktk.join('|')
        })
        .on('click', function(e) {
          // if (showids == 'qy8I4Y') {
          // if (jumbotron.jumbotronShowed && showids == jumbotron.getShowIds()) { // 本图有开屏
          //   se_monitor.customizeLog({
          //     event_name: 'click',
          //     para: {
          //       act: 'click',
          //       pid: data.ext.has //'p_jumbotron_small'
          //     }
          //   });
          // } else { //  本图无开屏
          //   se_monitor.customizeLog({
          //     event_name: 'click',
          //     para: {
          //       act: 'click',
          //       pid: data.ext.no //'p_recommend_right_ads'
          //     }
          //   });
          // }
          // }
        });

      $container.find('img').attr({
        src: ads.img,
        alt: '' //ads.title
      });
      $container.find('.img-title').hide();
      $container.find('p.img-ad').removeClass('not-ads').addClass('is-ads');

      // 展现打点
      (ads.imptk || []).forEach(function(item) {
        new Image().src = item;
      });
      impurl && (new Image().src = impurl + ads.imparg);
      // if (!jumbotronInited) { // 没有任何开屏
      //   se_monitor.customizeLog({
      //     event_name: 'track',
      //     para: {
      //       act: 'track',
      //       pid: 'p_recommend_right_ads'
      //     }
      //   });
      // } else { //有开屏
      //   if (showids !== jumbotron.getShowIds()) { // 开屏不是当前图，需要打track，是当前图的情况，jumbotron已经打了
      //     se_monitor.customizeLog({
      //       event_name: 'track',
      //       para: {
      //         act: 'track',
      //         pid: data.ext.no // 打no的pid
      //       }
      //     });
      //   }
      // }
    }

    //  开屏逻辑
    var doKaiping = function(data) {
      var impurl = data && data.impurl;
      var showids = data.showids;
      var ads = data && data.adspaces && data.adspaces[showids];
      ads = ads && ads.ads && ads.ads[0];

      if (!ads) return; // 没有广告数据，返回

      var $container = data.$container;
      jumbotron.init(ads);
      jumbotron.setShowIds(showids);
      jumbotron.setPid(data.ext.has);
      jumbotron.setReplay($container.find(".btn-replay"));
      jumbotron.setFadeOffset(data.getCenterOffset());
    }

    // 请求mediaV接口
    var requestMediaV = function(showids) {
      return $.ajax({
        url: '//show-3.mediav.com/s?type=1&of=4&newf=1',
        // url: '//show-g.mediav.com/s?type=1&of=4&newf=2',
        data: {
          // showids: showids,
          // mid: mid
          showid: showids,
          uid: mid
        },
        dataType: "jsonp",
        jsonp: "jsonp",
        jsonpCallback: "callback_mediav_" + showids,
        timeout: 3000
      });
    };


    // 有master，用master显示，否则选择slave的第一个
    var manageAd = function(datas) {
      var master = $.grep(datas, function(val) {
        return val.isMaster == true && isValidKaiping(val);
      });

      if (master.length) {
        master = master[0];
      } else {
        master = $.grep(datas, function(val) {
          return isValidKaiping(val);
        });

        master = master[0] ? master[0] : "";
      }

      if (master !== "") { // 有需要开屏的，进行开屏展示
        doKaiping(master);
      }

      $.each(datas, function(i, el) { // 无论如何都要替换广告
        // 替换广告
        doAd(el);

        setTimeout(function() {
          el.showHideContainer(true);
        }, 50);
      });
    };

    function MediaNode($container, showids, ext) {
      this.$container = $container;
      this.showids = showids;
      this.ext = ext;
      this.isMaster = false;
    }

    MediaNode.prototype = {
      // 显示或隐藏container
      showHideContainer: function(bool) {
        this.$container.css({
          visibility: !!bool ? "visible" : "hidden"
        });
      },

      // 获取中心的位置
      getCenterOffset: function() {
        var offset = this.$container.offset();

        var left = offset.left + this.$container.width() / 2;

        var spagesHeight = this.$container.parents(".wrapper").height();

        var bottom = spagesHeight - (this.$container.height() / 2) - offset.top;

        return { left: left, bottom: bottom };
      }
    };

    // 维护开屏展示的对象
    var showMediavMasterSlave = {
      slave: [],

      setMaster: function(master) {
        master.isMaster = true;
        this.master = master;

        return this;
      },

      addSlave: function(slave) {
        this.slave.push(slave);
        return this;
      },

      run: function() {
        var self = this;
        var nodes = this.master ? $.merge([this.master], this.slave) : this.slave;

        var reqs = $.map(nodes, function(el) {
          el.showHideContainer(false);

          return Q.resolve(requestMediaV(el.showids))
            .then(function(data) {
              var elObj = $.extend(true, {}, data, {
                "isMaster": el.isMaster,
                "$container": el.$container,
                "showHideContainer": el.showHideContainer,
                "showids": el.showids,
                "ext": el.ext,
                "getCenterOffset": el.getCenterOffset
              });

              return elObj;
            }, function() { // 失败时显示回来
              el.showHideContainer(true);
            });
        });

        Q.Promise.all(reqs)
          .then(function(rets) {
            // 取不回数据的直接回显
            var noData = $.grep(rets, function(el) {
              return el === undefined;
            });

            $.each(function(i, el) {
              el.showHideContainer(true);
            });

            // 其他的数据进入广告开屏逻辑
            var datas = $.grep(rets, function(el) {
              return el !== undefined;
            });

            manageAd.call(self, datas);
          });
      }
    };

    // var slave = new MediaNode($('[bk=recommend_right_ads_big]'), 'qy8I4Y');
    // var master = new MediaNode($('[bk=recommend_right_ads_small]'), 'a0ZVnP');

    var slave = new MediaNode($('[bk=recommend_right_ads_big]'), 'eFACGC', {
      "has": "p_jumbotron_small",
      "no": "p_recommend_right_ads"
    }); // 大图，副
    var master = new MediaNode($('[bk=recommend_right_ads_small]'), 'Rj3HQM', {
      "has": "p_jumbotron_rightbottom_small",
      "no": "p_rightbottom_smll"
    }); // 小图，主

    showMediavMasterSlave
      .setMaster(master)
      .addSlave(slave)
      .run();

    /*************************
     * liuguanyu 2017-09-10 以上
     *************************/

    // showcase start
    window.showcaseValid = false;
    window.showcaseVisible = false;
    var donttingMap = {};

    function renderShowcase($showcase, ads, impurl) {
      var $first = $showcase.find('.item-first');
      var $list = $showcase.find('.item-list ul');
      var $bottom = $showcase.find('.item-second');
      var $placeholder = $('.showcase-placeholder');
      var topGroupIndex = 0;
      var bottomGroupIndex = 0;
      var bottomSlideGroup = ads.splice(0, 1);
      var topSlideGroup = ads.slice(0, 4);
      var slideTimer = null;
      var isMouseEnter = false;
      var tpl = '<li class="thumb"><img src="" alt="" width="34" height="34"></li>';

      $('body').on('showcaseVisible' + $showcase.selector.replace('.', '-'), function(e) {
        dotting([topSlideGroup[0], bottomSlideGroup[0]]);
      });

      function renderTop() {
        render($first, topSlideGroup[topGroupIndex]);
        $list.find('li img').removeClass('active');
        $list.find('li').eq(topGroupIndex).find('img').addClass('active');
      }

      function renderBottom() {
        render($bottom, bottomSlideGroup[0]);
      }

      renderTop();
      renderBottom();
      dotting([topSlideGroup[0], bottomSlideGroup[0]]);

      function dotting(list) {
        if (list.length == 1 && topGroupIndex == 0) return;

        var keys = [];
        for (var i = 0; i < list.length; i++) {
          keys.push(list[i].curl);
        }
        var key = keys.join('_');

        if (!donttingMap[key] && showcaseVisible) {
          donttingMap[key] = true;

          var args = [];
          list.forEach(function(a) {
            (a.imptk || []).forEach(function(item) {
              item && (new Image().src = item);
            });

            args.push(a.imparg);
          });
          new Image().src = [impurl, args.join('.')].join('');
        }
      }

      function render($item, ad) {
        $item.find('a').attr({
          href: ad.curl,
          ctype: '1',
          'data-clktk': (ad.clktk || []).join(',')
        });

        var needClip = (ad.imgw == 280) && (ad.imgh == 200);
        var src = needClip ? ('http://imgx.mediav.com/rimg.png?size=180x180&img=' + ad.img + '&resizetype=3&quality=100&axisreset=1') : ad.img;

        $item.find('img').attr({
          src: src,
          alt: ad.desc
        });
        $item.find('.item-title').text(ad.desc);
      }

      function renderList() {
        var html = '';
        for (var i = 0; i < topSlideGroup.length; i++) {
          var ad = topSlideGroup[i];
          var $li = $(tpl);
          $li.find('img').attr('src', ad.img);
          html += $li[0].outerHTML;
        }
        $list.html(html);
      }

      function prePage() {
        topGroupIndex -= 1;
        bottomGroupIndex -= 1;

        if (topGroupIndex < 0) {
          topGroupIndex = topSlideGroup.length - 1;
        }

        renderTop();
        dotting([topSlideGroup[topGroupIndex]]);
      }

      function nextPage() {
        topGroupIndex += 1;
        bottomGroupIndex += 1;

        if (topGroupIndex > topSlideGroup.length - 1) {
          topGroupIndex = 0;
        }

        renderTop();
        dotting([topSlideGroup[topGroupIndex]]);
      }

      function startTimer() {
        var timeout = topGroupIndex == 0 ? 7e3 : 5e3;

        clearTimeout(slideTimer);
        slideTimer = setTimeout(function() {
          if (!isMouseEnter) {
            nextPage();
          }
          startTimer();
        }, timeout);
      }

      $placeholder.css('visibility', 'hidden');
      renderList();
      renderTop();
      renderBottom();

      $showcase.on('mouseenter', '.arrow-left', function(e) {
        e.preventDefault();
        e.stopPropagation();
        prePage();
        startTimer();
      }).on('click', '.arrow-left', function(e) {
        e.preventDefault();
        e.stopPropagation();
        prePage();
        startTimer();
      }).on('mouseenter', '.arrow-right', function(e) {
        e.preventDefault();
        e.stopPropagation();
        nextPage();
        startTimer();
      }).on('click', '.arrow-right', function(e) {
        e.preventDefault();
        e.stopPropagation();
        nextPage();
        startTimer();
      }).on('click', 'a', function(e) {
        var clktk = $(this).attr('data-clktk').split(',');
        clktk.forEach(function(item) {
          item && (new Image().src = item);
        });
      }).on('click', 'ul li', function(e) {
        e.preventDefault();
        topGroupIndex = $(this).index();
        renderTop();
      }).on('mouseenter', 'ul li', function(e) {
        e.preventDefault();
        topGroupIndex = $(this).index();
        renderTop();
      }).on('mouseenter', '.top img', function(e) {
        isMouseEnter = true;
      }).on('mouseleave', '.top img', function(e) {
        isMouseEnter = false;
      });

      setTimeout(function() {
        startTimer();
      }, 10000);
    }

    function fetchShowcase(showid, $container) {
      // @sea http://pages.juxiao.mediav.com/mdoc/pc_api/HTML/SceneWindowDockingDoc.html
      $.ajax({
        url: '//show-3.mediav.com/s',
        data: {
          type: 1,
          newf: 1,
          of: 4,
          showid: showid, //'niE1LX', //mTZATM',
          mid: mid,
          uid: mv_uid,
          impct: 5
        },
        dataType: 'jsonp',
        jsonp: 'jsonp',
        timeout: 5000,
        success: function(data) {
          var ads = (data || {}).ads || [];

          if (ads.length >= 5) {
            showcaseValid = true;
            renderShowcase($container, ads, data.impurl);
          }
        }
      });
    }

    fetchShowcase('mTZATM', $('.showcase-1'));
    fetchShowcase('niE1LX', $('.showcase-2'));
    // showcase end

    // init PageSlider
    $('.page .page-scrollbar').each(function() {
      new PageSlider($(this));
    });
  });
  </script>
  {qcms_script id="490964811" name="video_flow_all_ludashi"} {qcms_script id="490964819" name="ludashi_dotter"}
  <script src='http://s2.qhres.com/!8eec4728/monitor_baodian.js'></script>
  <script>
  (function() {
    var _oldGetClick = QIHOO_MONITOR_BAODIAN.data.getClick;
    QIHOO_MONITOR_BAODIAN.data.getClick = function(e) {
      var ret = _oldGetClick(e);
      ret['cat'] = $('#nav a.cur').text();
      return ret;
    };
  })();
  QIHOO_MONITOR_BAODIAN.setProject('QH_220_1').getTrack().getClickAndKeydown().getClickHeatmap(10, 1);
  </script>
</body>

</html>