<!doctype html>
<html>

<head>
  <meta charset="UTF-8">
  <title>mini</title>
  <base target="_blank">
  <script>
    try {
      external.Show(750, 492)
    } catch (err) { /*console.log(err)*/ }
  </script>
  <link rel="stylesheet" href="//s0.ssl.qhres.com/static/ad616d8a06e38078.css">
</head>

<body>
  <div></div>
  <div class="wrapper">
    <div class="doc-hd" id="doc-hd">
      <p class="logo f-l">
        <img src="http://p2.qhimg.com/t0196d3d0b214e8c6eb.png" alt="logo">
      </p>
      <p class="opteration f-r">
        <a href="#" class="setting"></a>
        <a href="#" class="min"></a>
        <a href="#" class="close"></a>
      </p>
    </div>
    <div class="mini_header">
      <!--
<p class="refresh" onclick="window.location.reload()">刷新</p>
-->
      <!--<p class="handover"><span><a href="javascript:void(0);">更多</a></span><i></i></p>-->
      <ul class="nav" id="nav">
        {qcms_block id="490388035" dtid="210084467" qcms-custom-preview="1"}
      </ul>
    </div>
    <div class="doc-bd" id="doc-bd">
      <div class="content">
        <div class="page" id="tab_rec" bk="mini_rec">
          <div class="inner">
            <div class="l f-l">
              <div bk="news_pic_left">
                {qcms_block id="490392512" dtid="490388118" count="1" width="180" height="194" qcms-custom-preview="1"}
              </div>
              <div bk="ent_pic">
                {qcms_block id="490392512" dtid="490680315" count="2" width="180" height="100" qcms-custom-preview="1"}
              </div>
            </div>
            <div class="m f-l">
              <div class="news">
                <div bk="news_text_top">
                  {qcms_block id="490392522" dtid="490388130" count="1" qcms-custom-preview="1"} {qcms_block id="490392530" dtid="490680479" count="4" qcms-custom-preview="1"}
                </div>
                <div bk="news_text_center">
                  {qcms_block id="490392522" dtid="490388197" count="1" qcms-custom-preview="1"} {qcms_block id="490392530" dtid="490680507" count="4" qcms-custom-preview="1"}
                </div>
                <div bk="ent_text">
                  {qcms_block id="490392522" dtid="490388247" count="1" qcms-custom-preview="1"} {qcms_block id="490392530" dtid="490680512" count="4" qcms-custom-preview="1"}
                </div>
              </div>
            </div>
            <div class="r f-r">
              <div bk="recommend_right_ads_big">
                {qcms_block id="490392512" dtid="490388310" count="1" width="180" height="191" qcms-custom-preview="1"}
              </div>
              <div bk="recommend_right_ads_small">
                {qcms_block id="490392512" dtid="210386518" count="2" width="180" height="100" qcms-custom-preview="1"}
              </div>
            </div>
            <div class='loading'></div>
            <div class='news-container'>
              <ul class='news-content-wrapper'></ul>
            </div>
          </div>
          <div class='page_home'></div>
          <div class="newsflow-tips" style="display: block;">&nbsp; 更多未读资讯<img src="http://p6.qhimg.com/d/inn/9ca1c978/arrow.gif" width="12" height="19"> <i></i> </div>
        </div>
        <div class="page" id="tab_game" bk="mini_game">
          <div class="inner">
            <div class="l f-l">
              <div bk="game_left_ads_big">
                {qcms_block id="490392512" dtid="210262409" count="1" width="180" height="194" qcms-custom-preview="1"}
              </div>
              <div bk="game_left_ads_small_1">
                {qcms_block id="490392512" dtid="210262412" count="1" width="180" height="100" qcms-custom-preview="1"}
              </div>
              <div bk="game_left_ads_small_2">
                {qcms_block id="490392512" dtid="210262416" count="1" width="180" height="100" qcms-custom-preview="1"}
              </div>
            </div>
            <div class="m f-l">
              <div class="news">
                <div bk="game_text_top">
                  {qcms_block id="490102734" dtid="210262418" count="1" qcms-custom-preview="1"} {qcms_block id="210082604" dtid="210262435" count="4" qcms-custom-preview="1"}
                </div>
                <div bk="game_text_center">
                  {qcms_block id="490102734" dtid="210262420" count="1" qcms-custom-preview="1"} {qcms_block id="210082604" dtid="210262437" count="4" qcms-custom-preview="1"}
                </div>
                <div bk="game_text_bottom">
                  {qcms_block id="490102734" dtid="210262423" count="1" qcms-custom-preview="1"} {qcms_block id="210082604" dtid="210262442" count="4" qcms-custom-preview="1"}
                </div>
              </div>
            </div>
            <div class="r f-r">
              <div bk="game_right_ads_big">
                {qcms_block id="490392512" dtid="210262425" count="1" width="180" height="274" qcms-custom-preview="1"}
              </div>
              <div bk="game_right_ads_small">
                {qcms_block id="490392512" dtid="210262429" count="1" width="180" height="128" qcms-custom-preview="1"}
              </div>
            </div>
            <div class='loading'></div>
            <div class='news-container'>
              <ul class='news-content-wrapper'></ul>
            </div>
          </div>
          <div class='page_home'></div>
          <div class="newsflow-tips" style="display: block;">&nbsp; 更多未读资讯<img src="http://p6.qhimg.com/d/inn/9ca1c978/arrow.gif" width="12" height="19"> <i></i> </div>
        </div>
        <div class="page" id="tab_military" bk="mini_military">
          <div class="inner">
            <div class="l f-l">
              {qcms_block id="490392512" dtid="490687793" count="1" width="180" height="194" qcms-custom-preview="1"} {qcms_block id="490392512" dtid="490687797" count="2" width="180" height="100" qcms-custom-preview="1"}
            </div>
            <div class="m f-l">
              <div class="news">
                <div>
                  {qcms_block id="490392522" dtid="490687802" count="1" qcms-custom-preview="1"} {qcms_block id="490392530" dtid="490687806" count="6" qcms-custom-preview="1"}
                </div>
                <div>
                  {qcms_block id="490392522" dtid="490687810" count="1" qcms-custom-preview="1"} {qcms_block id="490392530" dtid="490687825" count="3" qcms-custom-preview="1"}
                </div>
                <div>
                  {qcms_block id="490392522" dtid="490687836" count="1" qcms-custom-preview="1"} {qcms_block id="490392530" dtid="490687844" count="3" qcms-custom-preview="1"}
                </div>
              </div>
            </div>
            <div class="r f-r">
              {qcms_block id="490392512" dtid="490687868" count="1" width="180" height="194" qcms-custom-preview="1"} {qcms_block id="490392512" dtid="490687895" count="2" width="180" height="100" qcms-custom-preview="1"}
            </div>
            <div class='loading'></div>
            <div class='news-container'>
              <ul class='news-content-wrapper'></ul>
            </div>
          </div>
          <div class='page_home'></div>
          <div class="newsflow-tips" style="display: block;">&nbsp; 更多未读资讯<img src="http://p6.qhimg.com/d/inn/9ca1c978/arrow.gif" width="12" height="19"> <i></i> </div>
        </div>
        <div class="page" id="tab_life" bk="mini_life">
          <div class="inner">
            <div class="l f-l">
              {qcms_block id="490392512" dtid="490687905" count="1" width="180" height="194" qcms-custom-preview="1"} {qcms_block id="490392512" dtid="490687911" count="2" width="180" height="100" qcms-custom-preview="1"}
            </div>
            <div class="m f-l">
              <div class="news">
                <div>
                  {qcms_block id="490392522" dtid="490687915" count="1" qcms-custom-preview="1"} {qcms_block id="490392530" dtid="490687919" count="6" qcms-custom-preview="1"}
                </div>
                <div>
                  {qcms_block id="490392522" dtid="490687923" count="1" qcms-custom-preview="1"} {qcms_block id="490392530" dtid="490687929" count="3" qcms-custom-preview="1"}
                </div>
                <div>
                  {qcms_block id="490392522" dtid="490687933" count="1" qcms-custom-preview="1"} {qcms_block id="490392530" dtid="490687940" count="3" qcms-custom-preview="1"}
                </div>
              </div>
            </div>
            <div class="r f-r">
              {qcms_block id="490392512" dtid="490687946" count="1" width="180" height="194" qcms-custom-preview="1"} {qcms_block id="490392512" dtid="490687952" count="2" width="180" height="100" qcms-custom-preview="1"}
            </div>
            <div class='loading'></div>
            <div class='news-container'>
              <ul class='news-content-wrapper'></ul>
            </div>
          </div>
          <div class='page_home'></div>
          <div class="newsflow-tips" style="display: block;">&nbsp; 更多未读资讯<img src="http://p6.qhimg.com/d/inn/9ca1c978/arrow.gif" width="12" height="19"> <i></i> </div>
        </div>
        <div class="page" id="tab_finance" bk="mini_finance">
          <div class="inner">
            <div class="l f-l">
              {qcms_block id="490392512" dtid="490687959" count="1" width="180" height="194" qcms-custom-preview="1"} {qcms_block id="490392512" dtid="490687965" count="2" width="180" height="100" qcms-custom-preview="1"}
            </div>
            <div class="m f-l">
              <div class="news">
                <div>
                  {qcms_block id="490392522" dtid="490687969" count="1" qcms-custom-preview="1"} {qcms_block id="490392530" dtid="490687975" count="6" qcms-custom-preview="1"}
                </div>
                <div>
                  {qcms_block id="490392522" dtid="490687979" count="1" qcms-custom-preview="1"} {qcms_block id="490392530" dtid="490687983" count="3" qcms-custom-preview="1"}
                </div>
                <div>
                  {qcms_block id="490392522" dtid="490687990" count="1" qcms-custom-preview="1"} {qcms_block id="490392530" dtid="490687998" count="3" qcms-custom-preview="1"}
                </div>
              </div>
            </div>
            <div class="r f-r">
              {qcms_block id="490392512" dtid="490688003" count="1" width="180" height="194" qcms-custom-preview="1"} {qcms_block id="490392512" dtid="490688007" count="2" width="180" height="100" qcms-custom-preview="1"}
            </div>
            <div class='loading'></div>
            <div class='news-container'>
              <ul class='news-content-wrapper'></ul>
            </div>
          </div>
          <div class='page_home'></div>
          <div class="newsflow-tips" style="display: block;">&nbsp; 更多未读资讯<img src="http://p6.qhimg.com/d/inn/9ca1c978/arrow.gif" width="12" height="19"> <i></i> </div>
        </div>
        <div class="page" id="tab_tec" bk="mini_tec">
          <div class="inner">
            <div class="l f-l">
              {qcms_block id="490392512" dtid="490688011" count="1" width="180" height="194" qcms-custom-preview="1"} {qcms_block id="490392512" dtid="490688017" count="2" width="180" height="100" qcms-custom-preview="1"}
            </div>
            <div class="m f-l">
              <div class="news">
                <div>
                  {qcms_block id="490392522" dtid="490688023" count="1" qcms-custom-preview="1"} {qcms_block id="490392530" dtid="490688029" count="6" qcms-custom-preview="1"}
                </div>
                <div>
                  {qcms_block id="490392522" dtid="490688033" count="1" qcms-custom-preview="1"} {qcms_block id="490392530" dtid="490688038" count="3" qcms-custom-preview="1"}
                </div>
                <div>
                  {qcms_block id="490392522" dtid="490688045" count="1" qcms-custom-preview="1"} {qcms_block id="490392530" dtid="490688049" count="3" qcms-custom-preview="1"}
                </div>
              </div>
            </div>
            <div class="r f-r">
              {qcms_block id="490392512" dtid="490688064" count="1" width="180" height="194" qcms-custom-preview="1"} {qcms_block id="490392512" dtid="490688069" count="2" width="180" height="100" qcms-custom-preview="1"}
            </div>
            <div class='loading'></div>
            <div class='news-container'>
              <ul class='news-content-wrapper'></ul>
            </div>
          </div>
          <div class='page_home'></div>
          <div class="newsflow-tips" style="display: block;">&nbsp; 更多未读资讯<img src="http://p6.qhimg.com/d/inn/9ca1c978/arrow.gif" width="12" height="19"> <i></i> </div>
        </div>
        <div class="page" id="tab_sports" bk="mini_sports">
          <div class="inner">
            <div class="l f-l">
              {qcms_block id="490392512" dtid="210390761" count="1" width="180" height="194" qcms-custom-preview="1"} {qcms_block id="490392512" dtid="210390766" count="2" width="180" height="100" qcms-custom-preview="1"}
            </div>
            <div class="m f-l">
              <div class="news">
                <div>
                  {qcms_block id="490392522" dtid="210390770" count="1" qcms-custom-preview="1"} {qcms_block id="490392530" dtid="210390776" count="6" qcms-custom-preview="1"}
                </div>
                <div>
                  {qcms_block id="490392522" dtid="210390782" count="1" qcms-custom-preview="1"} {qcms_block id="490392530" dtid="210390787" count="3" qcms-custom-preview="1"}
                </div>
                <div>
                  {qcms_block id="490392522" dtid="210390791" count="1" qcms-custom-preview="1"} {qcms_block id="490392530" dtid="210390797" count="3" qcms-custom-preview="1"}
                </div>
              </div>
            </div>
            <div class="r f-r">
              {qcms_block id="490392512" dtid="210390801" count="1" width="180" height="194" qcms-custom-preview="1"} {qcms_block id="490392512" dtid="210390808" count="2" width="180" height="100" qcms-custom-preview="1"}
            </div>
            <div class='loading'></div>
            <div class='news-container'>
              <ul class='news-content-wrapper'></ul>
            </div>
          </div>
          <div class='page_home'></div>
          <div class="newsflow-tips" style="display: block;">&nbsp; 更多未读资讯<img src="http://p6.qhimg.com/d/inn/9ca1c978/arrow.gif" width="12" height="19"> <i></i> </div>
        </div>
        <div class="page" id="tab_car" bk="mini_car">
          <div class="inner">
            <div class="l f-l">
              {qcms_block id="490392512" dtid="210390812" count="1" width="180" height="194" qcms-custom-preview="1"} {qcms_block id="490392512" dtid="210390818" count="2" width="180" height="100" qcms-custom-preview="1"}
            </div>
            <div class="m f-l">
              <div class="news">
                <div>
                  {qcms_block id="490392522" dtid="210390822" count="1" qcms-custom-preview="1"} {qcms_block id="490392530" dtid="210390826" count="6" qcms-custom-preview="1"}
                </div>
                <div>
                  {qcms_block id="490392522" dtid="490688106" count="1" qcms-custom-preview="1"} {qcms_block id="490392530" dtid="490688112" count="3" qcms-custom-preview="1"}
                </div>
                <div>
                  {qcms_block id="490392522" dtid="490688120" count="1" qcms-custom-preview="1"} {qcms_block id="490392530" dtid="490688124" count="3" qcms-custom-preview="1"}
                </div>
              </div>
            </div>
            <div class="r f-r">
              {qcms_block id="490392512" dtid="490688129" count="1" width="180" height="194" qcms-custom-preview="1"} {qcms_block id="490392512" dtid="490688143" count="2" width="180" height="100" qcms-custom-preview="1"}
            </div>
            <div class='loading'></div>
            <div class='news-container'>
              <ul class='news-content-wrapper'></ul>
            </div>
          </div>
          <div class='page_home'></div>
          <div class="newsflow-tips" style="display: block;">&nbsp; 更多未读资讯<img src="http://p6.qhimg.com/d/inn/9ca1c978/arrow.gif" width="12" height="19"> <i></i> </div>
        </div>
        <div class="page" id="tab_constellation" bk="mini_constellation">
          <div class="inner">
            <div class="l f-l">
              {qcms_block id="490392512" dtid="490688156" count="1" width="180" height="194" qcms-custom-preview="1"} {qcms_block id="490392512" dtid="490688167" count="2" width="180" height="100" qcms-custom-preview="1"}
            </div>
            <div class="m f-l">
              <div class="news">
                <div>
                  {qcms_block id="490392522" dtid="490688178" count="1" qcms-custom-preview="1"} {qcms_block id="490392530" dtid="490688184" count="6" qcms-custom-preview="1"}
                </div>
                <div>
                  {qcms_block id="490392522" dtid="490688195" count="1" qcms-custom-preview="1"} {qcms_block id="490392530" dtid="490688201" count="3" qcms-custom-preview="1"}
                </div>
                <div>
                  {qcms_block id="490392522" dtid="490688215" count="1" qcms-custom-preview="1"} {qcms_block id="490392530" dtid="490688224" count="3" qcms-custom-preview="1"}
                </div>
              </div>
            </div>
            <div class="r f-r">
              {qcms_block id="490392512" dtid="490688230" count="1" width="180" height="194" qcms-custom-preview="1"} {qcms_block id="490392512" dtid="490688242" count="2" width="180" height="100" qcms-custom-preview="1"}
            </div>
            <div class='loading'></div>
            <div class='news-container'>
              <ul class='news-content-wrapper'></ul>
            </div>
          </div>
          <div class='page_home'></div>
          <div class="newsflow-tips" style="display: block;">&nbsp; 更多未读资讯<img src="http://p6.qhimg.com/d/inn/9ca1c978/arrow.gif" width="12" height="19"> <i></i> </div>
        </div>
        <div class="page" id="tab_digital" bk="mini_digital">
          <div class="inner">
            <div class="l f-l">
              {qcms_block id="490392512" dtid="210390876" count="1" width="180" height="194" qcms-custom-preview="1"} {qcms_block id="490392512" dtid="210390880" count="2" width="180" height="100" qcms-custom-preview="1"}
            </div>
            <div class="m f-l">
              <div class="news">
                <div>
                  {qcms_block id="490392522" dtid="210390884" count="1" qcms-custom-preview="1"} {qcms_block id="490392530" dtid="210390889" count="6" qcms-custom-preview="1"}
                </div>
                <div>
                  {qcms_block id="490392522" dtid="210390894" count="1" qcms-custom-preview="1"} {qcms_block id="490392530" dtid="490688336" count="3" qcms-custom-preview="1"}
                </div>
                <div>
                  {qcms_block id="490392522" dtid="490688340" count="1" qcms-custom-preview="1"} {qcms_block id="490392530" dtid="490688346" count="3" qcms-custom-preview="1"}
                </div>
              </div>
            </div>
            <div class="r f-r">
              {qcms_block id="490392512" dtid="490688362" count="1" width="180" height="194" qcms-custom-preview="1"} {qcms_block id="490392512" dtid="490688368" count="2" width="180" height="100" qcms-custom-preview="1"}
            </div>
            <div class='loading'></div>
            <div class='news-container'>
              <ul class='news-content-wrapper'></ul>
            </div>
          </div>
          <div class='page_home'></div>
          <div class="newsflow-tips" style="display: block;">&nbsp; 更多未读资讯<img src="http://p6.qhimg.com/d/inn/9ca1c978/arrow.gif" width="12" height="19"> <i></i> </div>
        </div>
        <div class="page" id="tab_girl" bk="mini_girl">
          <div class="inner">
            <div class="l f-l">
              {qcms_block id="490392512" dtid="490688376" count="1" width="180" height="194" qcms-custom-preview="1"} {qcms_block id="490392512" dtid="490688382" count="2" width="180" height="100" qcms-custom-preview="1"}
            </div>
            <div class="m f-l">
              <div class="news">
                <div>
                  {qcms_block id="490392522" dtid="490688386" count="1" qcms-custom-preview="1"} {qcms_block id="490392530" dtid="490688390" count="6" qcms-custom-preview="1"}
                </div>
                <div>
                  {qcms_block id="490392522" dtid="490688394" count="1" qcms-custom-preview="1"} {qcms_block id="490392530" dtid="490688408" count="3" qcms-custom-preview="1"}
                </div>
                <div>
                  {qcms_block id="490392522" dtid="490688416" count="1" qcms-custom-preview="1"} {qcms_block id="490392530" dtid="490688426" count="3" qcms-custom-preview="1"}
                </div>
              </div>
            </div>
            <div class="r f-r">
              {qcms_block id="490392512" dtid="490688433" count="1" width="180" height="194" qcms-custom-preview="1"} {qcms_block id="490392512" dtid="490688448" count="2" width="180" height="100" qcms-custom-preview="1"}
            </div>
            <div class='loading'></div>
            <div class='news-container'>
              <ul class='news-content-wrapper'></ul>
            </div>
          </div>
          <div class='page_home'></div>
          <div class="newsflow-tips" style="display: block;">&nbsp; 更多未读资讯<img src="http://p6.qhimg.com/d/inn/9ca1c978/arrow.gif" width="12" height="19"> <i></i> </div>
        </div>
        <div class="page" id="tab_culture" bk="mini_culture">
          <div class="inner">
            <div class="l f-l">
              {qcms_block id="490392512" dtid="490688454" count="1" width="180" height="194" qcms-custom-preview="1"} {qcms_block id="490392512" dtid="490688461" count="2" width="180" height="100" qcms-custom-preview="1"}
            </div>
            <div class="m f-l">
              <div class="news">
                <div>
                  {qcms_block id="490392522" dtid="490688467" count="1" qcms-custom-preview="1"} {qcms_block id="490392530" dtid="490688474" count="6" qcms-custom-preview="1"}
                </div>
                <div>
                  {qcms_block id="490392522" dtid="490688478" count="1" qcms-custom-preview="1"} {qcms_block id="490392530" dtid="490688482" count="3" qcms-custom-preview="1"}
                </div>
                <div>
                  {qcms_block id="490392522" dtid="490688487" count="1" qcms-custom-preview="1"} {qcms_block id="490392530" dtid="490688497" count="3" qcms-custom-preview="1"}
                </div>
              </div>
            </div>
            <div class="r f-r">
              {qcms_block id="490392512" dtid="490688502" count="1" width="180" height="194" qcms-custom-preview="1"} {qcms_block id="490392512" dtid="490688506" count="2" width="180" height="100" qcms-custom-preview="1"}
            </div>
            <div class='loading'></div>
            <div class='news-container'>
              <ul class='news-content-wrapper'></ul>
            </div>
          </div>
          <div class='page_home'></div>
          <div class="newsflow-tips" style="display: block;">&nbsp; 更多未读资讯<img src="http://p6.qhimg.com/d/inn/9ca1c978/arrow.gif" width="12" height="19"> <i></i> </div>
        </div>
        <div class="page" id="tab_video" bk="mini_video">
          <div class="inner">
            <div class="l f-l">
              <div bk="video_left_ads_big">
                {qcms_block id="490392540" dtid="210240491" count="1" width="180" height="194" qcms-custom-preview="1"}
              </div>
              <div bk="video_left_ads_small_1">
                {qcms_block id="490392540" dtid="210240489" count="1" width="180" height="100" qcms-custom-preview="1"}
              </div>
              <div bk="video_left_ads_small_2">
                {qcms_block id="490392540" dtid="210240487" count="1" width="180" height="100" qcms-custom-preview="1"}
              </div>
            </div>
            <div class="m f-l">
              <div class="news">
                <div bk="video_text_top">
                  {qcms_block id="490392522" dtid="210240481" count="1" qcms-custom-preview="1"} {qcms_block id="490392530" dtid="210240479" count="4" qcms-custom-preview="1"}
                </div>
                <div bk="video_text_center">
                  {qcms_block id="490392522" dtid="210240477" count="1" qcms-custom-preview="1"} {qcms_block id="490392530" dtid="210240475" count="4" qcms-custom-preview="1"}
                </div>
                <div bk="video_text_bottom">
                  {qcms_block id="490392522" dtid="210240473" count="1" qcms-custom-preview="1"} {qcms_block id="490392530" dtid="210240471" count="4" qcms-custom-preview="1"}
                </div>
              </div>
            </div>
            <div class="r f-r">
              {qcms_block id="490392512" dtid="210240485" count="1" width="180" height="194" qcms-custom-preview="1"} {qcms_block id="490392512" dtid="210240483" count="2" width="180" height="100" qcms-custom-preview="1"}
            </div>
            <div class='loading'></div>
            <div class='news-container'>
              <ul class='news-content-wrapper'></ul>
            </div>
          </div>
          <div class='page_home'></div>
          <div class="newsflow-tips" style="display: block;">&nbsp; 更多未读资讯<img src="http://p6.qhimg.com/d/inn/9ca1c978/arrow.gif" width="12" height="19"> <i></i> </div>
        </div>
        <div class="page" id="tab_live" bk="mini_live">
          <div class="inner">
            <div class="p-top g-clear">
              <div class="p-top-left">
                {qcms_block id="210360277" dtid="490387825" count="1" qcms-custom-preview="1"}
              </div>
              <div class="p-top-middle">
                <div class="p-top-middle-title">
                  <p>
                    {qcms_block id="210360285" dtid="210230589" count="1" qcms-custom-preview="1"}
                  </p>
                </div>
                <div class="p-top-middle-list">
                  {qcms_block id="210360290" dtid="210289915" count="5" qcms-custom-preview="1"}
                </div>
              </div>
              <div class="p-top-right">
                {qcms_block id="210360277" dtid="490387832" count="1" qcms-custom-preview="1"}
              </div>
            </div>
            <div class="p-bottom">
              <ul class="p-bottom-list g-clear">
                {qcms_block id="210360295" dtid="210230619" count="8" qcms-custom-preview="1"}
              </ul>
            </div>
            <div class='loading'></div>
            <div class='news-container'>
              <ul class='news-content-wrapper'></ul>
            </div>
          </div>
          <div class='page_home'></div>
          <div class="newsflow-tips" style="display: block;">&nbsp; 更多未读资讯<img src="http://p6.qhimg.com/d/inn/9ca1c978/arrow.gif" width="12" height="19"> <i></i> </div>
        </div>
        <div class="page" id="tab_shopping" bk="mini_shopping">
          <div class="inner">
            <div class="l f-l">
              <div bk="shopping_left_top">
                {qcms_block id="490392512" dtid="490739491" count="1" width="180" height="194" qcms-custom-preview="1"}
              </div>
              <div bk="shopping_left_bottom">
                {qcms_block id="490392512" dtid="210417527" count="2" width="180" height="100" qcms-custom-preview="1"}
              </div>
            </div>
            <div class="m f-l">
              <div class="news">
                <div bk="shopping_text_top">
                  {qcms_block id="490392522" dtid="210417529" count="1" qcms-custom-preview="1"} {qcms_block id="490392530" dtid="490739504" count="4" qcms-custom-preview="1"}
                </div>
                <div bk="shopping_text_center">
                  {qcms_block id="490392522" dtid="490739510" count="1" qcms-custom-preview="1"} {qcms_block id="490392530" dtid="210417532" count="4" qcms-custom-preview="1"}
                </div>
                <div bk="shopping_text_bottom">
                  {qcms_block id="490392522" dtid="490739524" count="1" qcms-custom-preview="1"} {qcms_block id="490392530" dtid="490739526" count="4" qcms-custom-preview="1"}
                </div>
              </div>
            </div>
            <div class="r f-r">
              <div bk="shopping_right_top">
                {qcms_block id="490392512" dtid="210417535" count="1" width="180" height="191" qcms-custom-preview="1"}
              </div>
              <div bk="shopping_right_bottom">
                {qcms_block id="490392512" dtid="210417537" count="2" width="180" height="100" qcms-custom-preview="1"}
              </div>
            </div>
            <div class='loading'></div>
            <div class='news-container'>
              <ul class='news-content-wrapper'></ul>
            </div>
          </div>
          <div class='page_home'></div>
          <!--<div class="newsflow-tips" style="display: block;">&nbsp; 更多未读资讯<img src="http://p6.qhimg.com/d/inn/9ca1c978/arrow.gif" width="12" height="19"> <i></i> </div>-->
        </div>
        <div class="page" id="tab_news" bk="mini_news">
          <div class="inner">
            <div class="l f-l">
              {qcms_block id="490392512" dtid="490680392" count="1" width="180" height="194" qcms-custom-preview="1"} {qcms_block id="490392512" dtid="490680408" count="2" width="180" height="100" qcms-custom-preview="1"}
            </div>
            <div class="m f-l">
              <div class="news">
                <div>
                  {qcms_block id="490392522" dtid="490680430" count="1" qcms-custom-preview="1"} {qcms_block id="490392530" dtid="210386612" count="6" qcms-custom-preview="1"}
                </div>
                <div>
                  {qcms_block id="490392522" dtid="210392378" count="1" qcms-custom-preview="1"} {qcms_block id="490392530" dtid="210386606" count="3" qcms-custom-preview="1"}
                </div>
                <div>
                  {qcms_block id="490392522" dtid="210386593" count="1" qcms-custom-preview="1"} {qcms_block id="490392530" dtid="490680450" count="3" qcms-custom-preview="1"}
                </div>
              </div>
            </div>
            <div class="r f-r">
              {qcms_block id="490392512" dtid="210386601" count="1" width="180" height="194" qcms-custom-preview="1"} {qcms_block id="490392512" dtid="490680446" count="2" width="180" height="100" qcms-custom-preview="1"}
            </div>
            <div class='loading'></div>
            <div class='news-container'>
              <ul class='news-content-wrapper'></ul>
            </div>
          </div>
          <div class='page_home'></div>
          <div class="newsflow-tips" style="display: block;">&nbsp; 更多未读资讯<img src="http://p6.qhimg.com/d/inn/9ca1c978/arrow.gif" width="12" height="19"> <i></i> </div>
        </div>
        <div class="page" id="tab_ent" bk="mini_ent">
          <div class="inner">
            <div class="l f-l">
              {qcms_block id="490392512" dtid="490680909" count="1" width="180" height="194" qcms-custom-preview="1"} {qcms_block id="490392512" dtid="210386872" count="2" width="180" height="100" qcms-custom-preview="1"}
            </div>
            <div class="m f-l">
              <div class="news">
                <div>
                  {qcms_block id="490392522" dtid="490680947" count="1" qcms-custom-preview="1"} {qcms_block id="490392530" dtid="490680955" count="6" qcms-custom-preview="1"}
                </div>
                <div>
                  {qcms_block id="490392522" dtid="490685151" count="1" qcms-custom-preview="1"} {qcms_block id="490392530" dtid="490685161" count="3" qcms-custom-preview="1"}
                </div>
                <div>
                  {qcms_block id="490392522" dtid="490685174" count="1" qcms-custom-preview="1"} {qcms_block id="490392530" dtid="490685190" count="3" qcms-custom-preview="1"}
                </div>
              </div>
            </div>
            <div class="r f-r">
              {qcms_block id="490392512" dtid="210389258" count="1" width="180" height="194" qcms-custom-preview="1"} {qcms_block id="490392512" dtid="490685202" count="2" width="180" height="100" qcms-custom-preview="1"}
            </div>
            <div class='loading'></div>
            <div class='news-container'>
              <ul class='news-content-wrapper'></ul>
            </div>
          </div>
          <div class='page_home'></div>
          <div class="newsflow-tips" style="display: block;">&nbsp; 更多未读资讯<img src="http://p6.qhimg.com/d/inn/9ca1c978/arrow.gif" width="12" height="19"> <i></i> </div>
        </div>
        <div class="page" id="tab_society" bk="mini_society">
          <div class="inner">
            <div class="l f-l">
              {qcms_block id="490392512" dtid="490685206" count="1" width="180" height="194" qcms-custom-preview="1"} {qcms_block id="490392512" dtid="490685214" count="2" width="180" height="100" qcms-custom-preview="1"}
            </div>
            <div class="m f-l">
              <div class="news">
                <div>
                  {qcms_block id="490392522" dtid="490685227" count="1" qcms-custom-preview="1"} {qcms_block id="490392530" dtid="490685239" count="6" qcms-custom-preview="1"}
                </div>
                <div>
                  {qcms_block id="490392522" dtid="210389279" count="1" qcms-custom-preview="1"} {qcms_block id="490392530" dtid="490685253" count="3" qcms-custom-preview="1"}
                </div>
                <div>
                  {qcms_block id="490392522" dtid="490685392" count="1" qcms-custom-preview="1"} {qcms_block id="490392530" dtid="490686044" count="3" qcms-custom-preview="1"}
                </div>
              </div>
            </div>
            <div class="r f-r">
              {qcms_block id="490392512" dtid="490686932" count="1" width="180" height="194" qcms-custom-preview="1"} {qcms_block id="490392512" dtid="490686982" count="2" width="180" height="100" qcms-custom-preview="1"}
            </div>
            <div class='loading'></div>
            <div class='news-container'>
              <ul class='news-content-wrapper'></ul>
            </div>
          </div>
          <div class='page_home'></div>
          <div class="newsflow-tips" style="display: block;">&nbsp; 更多未读资讯<img src="http://p6.qhimg.com/d/inn/9ca1c978/arrow.gif" width="12" height="19"> <i></i> </div>
        </div>
        <div class="page" id="tab_joke" bk="mini_joke">
          <div class="inner">
            <div class="p-top g-clear">
              <div class="p-top-left">
                {qcms_block id="210360277" dtid="490388095" count="1" qcms-custom-preview="1"}
              </div>
              <div class="p-top-middle">
                <div class="p-top-middle-title">
                  <p>
                    {qcms_block id="210360285" dtid="490388099" count="1" qcms-custom-preview="1"}
                  </p>
                </div>
                <div class="p-top-middle-line">
                  <p>
                    {qcms_block id="490387663" dtid="490388101" count="3" qcms-custom-preview="1"}
                  </p>
                </div>
                <div class="p-top-middle-list">
                  <div class="p-top-middle-list-li">
                    <i></i> {qcms_block id="490387663" dtid="490388103" count="2" qcms-custom-preview="1"}
                  </div>
                  <div class="p-top-middle-list-li">
                    <i></i> {qcms_block id="490387663" dtid="490388105" count="3" qcms-custom-preview="1"}
                  </div>
                  <div class="p-top-middle-list-li">
                    <i></i> {qcms_block id="490387663" dtid="490388107" count="3" qcms-custom-preview="1"}
                  </div>
                  <div class="p-top-middle-list-li">
                    <i></i> {qcms_block id="490387663" dtid="490388111" count="3" qcms-custom-preview="1"}
                  </div>
                </div>
              </div>
              <div class="p-top-right">
              {qcms_block id="210328876" dtid="490388097" count="1" qcms-custom-preview="1"}
              </div>
            </div>
            <div class="p-bottom">
              <ul class="p-bottom-list g-clear">
                {qcms_block id="210360295" dtid="490388114" count="8" qcms-custom-preview="1"}
              </ul>
            </div>
            <div class='loading'></div>
            <div class='news-container'>
              <ul class='news-content-wrapper'></ul>
            </div>
          </div>
          <div class='page_home'></div>
          <div class="newsflow-tips" style="display: block;">&nbsp; 更多未读资讯<img src="http://p6.qhimg.com/d/inn/9ca1c978/arrow.gif" width="12" height="19"> <i></i> </div>
        </div>
        <div class="page" id="tab_movie" bk="mini_movie">
          <div class="inner">
            <div class="l f-l">
              {qcms_block id="490392512" dtid="490421962" count="1" width="180" height="194" qcms-custom-preview="1"} {qcms_block id="490392512" dtid="490421960" count="2" width="180" height="100" qcms-custom-preview="1"}
            </div>
            <div class="m f-l">
              <div class="news">
                <div>
                  {qcms_block id="490392522" dtid="210249248" count="1" qcms-custom-preview="1"} {qcms_block id="490392530" dtid="210249246" count="6" qcms-custom-preview="1"}
                </div>
                <div>
                  {qcms_block id="490392522" dtid="210249244" count="1" qcms-custom-preview="1"} {qcms_block id="490392530" dtid="210249242" count="3" qcms-custom-preview="1"}
                </div>
                <div>
                  {qcms_block id="490392522" dtid="210249240" count="1" qcms-custom-preview="1"} {qcms_block id="490392530" dtid="210249237" count="3" qcms-custom-preview="1"}
                </div>
              </div>
            </div>
            <div class="r f-r">
              {qcms_block id="490392512" dtid="490421958" count="1" width="180" height="194" qcms-custom-preview="1"} {qcms_block id="490392512" dtid="210249250" count="2" width="180" height="100" qcms-custom-preview="1"}
            </div>
            <div class='loading'></div>
            <div class='news-container'>
              <ul class='news-content-wrapper'></ul>
            </div>
          </div>
          <div class='page_home'></div>
          <div class="newsflow-tips" style="display: block;">&nbsp; 更多未读资讯<img src="http://p6.qhimg.com/d/inn/9ca1c978/arrow.gif" width="12" height="19"> <i></i> </div>
        </div>
        <!--<div class="page" id="tab_shopping" bk="mini_shopping">
            <iframe src="//pages.juxiao.mediav.com/ad/mi ni/showcase-708x418-1.html#vIp654" scrolling="no" frameborder="no"></iframe>
        </div>-->
      </div>
    </div>
  </div>
  <!--引入打点代码-->
  <script src="//s0.ssl.qhimg.com/static/2afc71670295f3b8/jquery,qw.core.js">
  </script>
  <script src="//s0.ssl.qhimg.com/static/ab69bff62405ffb7/utils.js">
  </script>
  <script src="//s0.ssl.qhimg.com/static/f5407c785655e6a1/monitor_analytic.js"></script>
  <!--[if lt IE 9 ]>
  <script src="//s0.ssl.qhimg.com/!fbaf1326/es5-shim.min.js"></script>
  <script src="//s0.ssl.qhimg.com/!2d038e37/es5-sham.min.js"></script>
  <script src="//s0.ssl.qhimg.com/!10cc5473/json2.js"></script>
  <![endif]-->
  {qcms_script id="210238996"}
  <script id="tpl" type="template">
      <li class="{{news_class}}">
          <div class="pic_box2">
              <a href="{{url}}" title="{{title}}">
                  <div class="pic">
                      <img src="{{image}}">
                  </div>
                  <div class="txt">
                      <div class="tit">
                          <span class="fl">{{title|ellipsis26}}</span>
                      </div>
                  </div>
                  <span class="{{type}}"></span>
                  <span class="ico_ad"></span>
              </a>
          </div>
      </li>
  </script>
  <script src="//s0.ssl.qhres.com/static/0a6a90e4b280ea5d.js"></script>
  <script>
    (function() {
      monitor.setProject('QH_132_13').getTrack().getClickAndKeydown().getClickHeatmap(10, 1)
      // 改写数据中心点击打点
      // 带上所属的 分类
      var oldClickFn = monitor.data.getClick
      monitor.data.getClick = function(e) {
          e = e || event
          var $el = 'target' in e ? $(e.target) : $(e.srcElement)
          var $page = $el.closest('.page')
          var $nav = $el.closest('.nav')
          var param = oldClickFn(e)
          if ($page.length) {
            param.cate = $page.attr('id')
          } else if ($nav.length) {
            //param.cate = $el.attr("id").replace(/^nav/, "tab");
          }
          return param
        }
        // 获取弹窗信息
      var mid = ''
      var version = ''
      try {
        mid = window.external.GetMid()
      } catch (e) {}
      try {
        version = window.external.GetVersion()
      } catch (e) {}
      // 首屏打点
      var track = monitor.data.getTrack()
      track = sg_monitor.mix({}, track, {
        tab: 'first'
      })
      monitor.log(track, 'track')
      // 初始化自定义打点
      sg_monitor.setDefaultData({
        _mid: mid,
        _version: version
      })
      sg_monitor.setUrl(location.protocol + '//mini.safe.360.cn')
      sg_monitor.setDefaultMethod('POST')
      var sg_track = sg_monitor.mix({}, track, monitor.data.getBase())
      // 自定义首屏打点
      sg_monitor.log(sg_track, 'track')
    })()
  </script>
  <script>
    // 新闻展示打点
    // 记录新闻的 title 和 所述分类
    // 其中 title 经过了 md5 加密
    function logNews($page) {
      var news = []
      var sg_news = []
      var sg_urls = []
      var tab = $page.attr('id')
      $page.find('.inner a').each(function(i, el) {
        var $el = $(el)
        var mtitle = $el.data('mtitle')
        var title = $el.data('title')
        var url = $el.attr('href')
        news.push(mtitle)
        sg_news.push(title)
        sg_urls.push(url)
      })
      // cate是所述分类
      // 有可能失败 因为 GET 的长度限制
      monitor.log({
        news: news,
        cate: tab
      }, 'track')
      // 卫士自定义打点
      var data = monitor.data.getBase()
      data = sg_monitor.mix({}, data, {
        news: sg_news,
        urls: sg_urls,
        cate: tab
      })
      sg_monitor.log(data, 'track')
    }

    // tab展示打点
    function logTabs($page) {
      //var tab = $page.attr("id").replace(/^tab_/, "");
      var tab = $page.attr('id')
      monitor.log({
        tab: tab
      }, 'track')

      // 卫士自定义打点
      var data = monitor.data.getBase()
      data = sg_monitor.mix({}, data, {
        tab: tab
      })
      sg_monitor.log(data, 'track')
    }

    // 获取翻转的html
    function getHandoverHtml($nav) {
      var len = $nav.find('li a').length
      var flipIndex = 11
      return len > flipIndex ? $('#nav li a').eq(flipIndex)[0].outerHTML : ''
    }

    (function() {
      // 替换来源标识
      var reg = /(from=mini)|(src=mini)/
      $('a').each(function(i, el) {
        var $el = $(el)
        var href = $el.attr('href')
        if (reg.test(href)) {
          $el.attr('href', href.replace(reg, function(match, from, src) {
            if (from) {
              return 'from=safemini'
            } else if (src) {
              return 'src=safemini'
            }
          }))
        }
      })
      // 首个tab的打点
      var tab = $('#nav li a').first().attr('id').replace(/^nav_/, '')
      var $page = $('#tab_' + tab)
      logTabs($page)
      logNews($page)
      // 卫士自定义打点
      // 点击
      $('body').on('click', 'a:not(.page .inner a)', function(e) {
        var data = monitor.data.getClick(e)
        var base = monitor.data.getBase()
        data = sg_monitor.mix({}, data, base)
        sg_monitor.log(data, 'click')
      })
    })()
    var mini = {
      $page: $('.page'),
      $nav: $('#nav'),
      firstCarouselDelay: null,
      pageShowDelay: 300,
      timerId: null,
      clear: function() {
        clearTimeout(mini.firstCarouselDelay)
        clearInterval(mini.timerId)
      },
      hoverPageAction: function($channel, iftrack) {
        mini.clear()
        var self = this
        self.$page.hide()
        self.$nav.find('a').removeClass('cur')
        $channel.addClass('cur')
        var pid = $channel.attr('id')
        var cate = pid.slice(4)
        var $tarcon = $('#tab_' + cate)
        if ($tarcon.find('iframe').length && $tarcon.find('iframe').attr('src') == '') {
          var tempsrc = $tarcon.find('iframe').attr('tempsrc')
          $tarcon.find('iframe').attr('src', tempsrc)
        }
        $tarcon.show()
        // 图片懒加载
        Mini.loadImg($tarcon)
        // 新闻展现 test
        if (iftrack) {
          logNews($tarcon)
          logTabs($tarcon)
        }
      },
      orderFn: function() {
        var self = this
        var index = 1
        var count = $('#nav li').length
        var flipNum = 11
        var liveStr = getHandoverHtml(this.$nav)
        self.timerId = setInterval(function() {
          if (index < count && index != flipNum) {
            $('#nav li').eq(index).siblings('li').find('a').removeClass('cur')
            var $channel = $('#nav li').eq(index).find('a').addClass('cur')
            mini.hoverPageAction($channel, true)
            //$(".content .page").hide().eq(index).show();
            index++
          } else if (index == flipNum && flipNum < count) {
            $('#nav li').eq(index).siblings('li').find('a').removeClass('cur')
            var $channel = $('#nav li').eq(index).find('a').addClass('cur')
            mini.hoverPageAction($channel, true)
            //$(".content .page").hide().eq(index).show();
            $('.nav').animate({
              'top': '-38px'
            }, 300).addClass('top38')
            $('.handover').find('span').html('返回')
            $('.handover').find('i').addClass('rotate').removeClass('rotate-back')
            index++
          } else if (index == count) {
            //$("#nav li").eq(0).mouseenter();
            var $channel = $('#nav li').eq(0).find('a').addClass('cur')
            mini.hoverPageAction($channel, true)
            $('.nav').animate({
              'top': '1px'
            }, 300).removeClass('top38')
            $('.handover').find('span').html(liveStr)
            $('.handover').find('i').removeClass('rotate').addClass('rotate-back')
            clearInterval(self.timerId)
          }
        }, 3000)
      },
      replaceBackBtn: function() {
        var $handover = $('<p class="handover"><span><a href="javascript:void(0);">更多</a></span><i></i></p>')
        $('.mini_header').prepend($handover)
        $('.handover span').html($('#nav li a').eq(11)[0].outerHTML)
      }
    }
    $(function() {
      mini.firstCarouselDelay = setTimeout(function() {
        mini.orderFn()
      }, 10 * 1000)
      // 只有个数足够的时候 才调用
      var len = mini.$nav.find('li a').length
      if (len > 11) {
        mini.replaceBackBtn()
      }
      $('#tab_rec').show()
      $('.wrapper').on('click', 'a', function(e) {
        // var pid = $('#nav').find('.cur').attr('id');
        e.preventDefault()
        var href = $(this).attr('href')
        try {
          external.OpenUrl(href)
        } catch (err) {
          window.open(href)
        }
      })
      $('#nav').on('mouseenter', 'li', function() {
        mini.clear()
        var $item = $(this).find('a')
        // 避免不必要的更新和打点
        if ($item.hasClass('cur')) {
          return
        }
        mini.timerId = setTimeout(function() {
          mini.hoverPageAction($item, true)
        }, mini.pageShowDelay)
      })
      $('#nav').on('click', 'li', function() {
        mini.clear()
        var $item = $(this).find('a')
        // click 的时候 不做额外展现打点
        var track = !$item.hasClass('cur')
        mini.hoverPageAction($item, track)
      })
      $('#nav').on('mouseleave', 'li', function() {
        mini.clear()
      })
      //频道切换
      var edgeIndex = 11
      var liveStr = getHandoverHtml(mini.$nav)
      // 展示下一页
      function togglePage(context) {
        // 正在动画 退出
        if (togglePage.animating === true) {
          return
        }
        mini.clear()
        // 标记正在动画
        togglePage.animating = true
        var $nav = $('.nav')
        var className = 'top38'
        if ($nav.hasClass(className)) {
          $nav.animate({
            'top': '1px'
          }, 300, function() {
            togglePage.animating = false
          }).removeClass('top38')
          $(context).find('span').html(liveStr)
          $(context).find('i').removeClass('rotate').addClass('rotate-back')
          $('#nav li:first-child()').siblings('li').find('a').removeClass('cur')
          $('#nav li:first-child()').mouseenter().find('a').addClass('cur')
          // 展现打点
          var tab = $('#nav li a').first().attr('id').replace(/^nav_/, '')
          var $page = $('#tab_' + tab)
          logTabs($page)
          logNews($page)
        } else {
          $nav.animate({
            'top': '-38px'
          }, 300, function() {
            togglePage.animating = false
          }).addClass(className)
          $(context).find('span').html('返回')
          $(context).find('i').addClass('rotate').removeClass('rotate-back')
          $('#nav li a').eq(edgeIndex).closest('li').mouseenter()
          // 展现打点
          var tab = $('#nav li a').eq(edgeIndex).attr('id').replace(/^nav_/, '')
          var $page = $('#tab_' + tab)
          logTabs($page)
          logNews($page)
        }
      }
      $('.handover').on('mouseenter', function() {
        togglePage(this)
      })
      //返回按钮
      $('.handover').on('click', function() {
        if ($(this).find('span').text() == '返回') {
          $('.nav').animate({
            'top': '1px'
          }, 300).removeClass('top38')
          $(this).find('span').html(liveStr)
          $(this).find('i').removeClass('rotate').addClass('rotate-back')
          $('#nav li:first-child()').siblings('li').find('a').removeClass('cur')
          $('#nav li:first-child()').mouseenter().find('a').addClass('cur')
        }
      })
    })
  </script>
  <script>
    (function() {
      Mini.fetchCate()
      // 鼠标进入窗体 直接停止轮播
      $('.page').on('mouseover', function() {
        mini.clear()
        $('.page').off('mouseover')
      })
      var cates = $.map($('#nav li a:not([data-iframe]):not([data-noscroll])'), function(el) {
        return $(el).attr('id').replace(/^nav_/, '')
      })
      $.each(cates, function(i, cate) {
        var $page = $('#tab_' + cate)
        $page.show()
        Mini.init(cate)
        if (i !== 0) {
          $page.hide()
        }
      })
    })()
  </script>
</body>

</html>